// lib/reports/templates/cbam.ts
// CBAM Report — HTML template (rendered to PDF for human review)
// The actual XML submission file is generated by lib/reports/cbam-xml.ts

import { brandStyles } from "./shared";
import type { CbamGoodsItem } from "../cbam-xml";

export interface CbamHtmlData {
  orgName: string;
  logoDataUri?: string;
  periodLabel: string;
  periodStart: Date;
  periodEnd: Date;
  publishedAt: Date;
  publishedBy: string;
  declarantEori?: string;
  goodsItems: CbamGoodsItem[];
  factorLibrary: string;
  methodology: string;
  gwpVersion: string;
}

function fmt(d: Date) {
  return d.toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
}

function fmtN(n: number, dp = 3) {
  return n.toLocaleString("en-GB", { minimumFractionDigits: dp, maximumFractionDigits: dp });
}

export function renderCbamHtml(data: CbamHtmlData): string {
  const totalDirect   = data.goodsItems.reduce((s, g) => s + g.directEmbeddedCo2eTonnes, 0);
  const totalIndirect = data.goodsItems.reduce((s, g) => s + g.indirectEmbeddedCo2eTonnes, 0);
  const totalEmbedded = totalDirect + totalIndirect;
  const totalQty      = data.goodsItems.reduce((s, g) => s + g.quantityTonnes, 0);

  const logoHtml = data.logoDataUri
    ? `<img src="${data.logoDataUri}" alt="${data.orgName} logo" style="height:48px;max-width:200px;object-fit:contain;">`
    : `<span style="font-size:1.1rem;font-weight:700;color:#228B22;">${data.orgName}</span>`;

  const rowsHtml = data.goodsItems.map((item, i) => {
    const total = item.directEmbeddedCo2eTonnes + item.indirectEmbeddedCo2eTonnes;
    const specific = item.quantityTonnes > 0 ? total / item.quantityTonnes : 0;
    return `
      <tr style="background:${i % 2 === 0 ? "#ffffff" : "#f8fafb"};">
        <td style="padding:10px 14px;border-bottom:1px solid #e5e7eb;font-size:0.82rem;font-weight:600;color:#228B22;">${item.cnCode}</td>
        <td style="padding:10px 14px;border-bottom:1px solid #e5e7eb;font-size:0.82rem;">${item.description}</td>
        <td style="padding:10px 14px;border-bottom:1px solid #e5e7eb;font-size:0.82rem;">${item.installation?.country ?? "—"}</td>
        <td style="padding:10px 14px;border-bottom:1px solid #e5e7eb;font-size:0.82rem;text-align:right;font-variant-numeric:tabular-nums;">${fmtN(item.quantityTonnes)}</td>
        <td style="padding:10px 14px;border-bottom:1px solid #e5e7eb;font-size:0.82rem;text-align:right;font-variant-numeric:tabular-nums;">${fmtN(item.directEmbeddedCo2eTonnes)}</td>
        <td style="padding:10px 14px;border-bottom:1px solid #e5e7eb;font-size:0.82rem;text-align:right;font-variant-numeric:tabular-nums;">${fmtN(item.indirectEmbeddedCo2eTonnes)}</td>
        <td style="padding:10px 14px;border-bottom:1px solid #e5e7eb;font-size:0.82rem;text-align:right;font-weight:700;font-variant-numeric:tabular-nums;">${fmtN(total)}</td>
        <td style="padding:10px 14px;border-bottom:1px solid #e5e7eb;font-size:0.82rem;text-align:right;font-variant-numeric:tabular-nums;">${fmtN(specific, 4)}</td>
        <td style="padding:10px 14px;border-bottom:1px solid #e5e7eb;font-size:0.82rem;text-align:right;font-variant-numeric:tabular-nums;">${fmtN(item.carbonPricePaidGbp, 2)}</td>
      </tr>`;
  }).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>CBAM Report — ${data.orgName} — ${data.periodLabel}</title>
<style>
${brandStyles()}
body { font-family: 'Segoe UI', Arial, sans-serif; color: #333; background: #fff; font-size: 0.88rem; }
.header { background: #228B22; color: white; padding: 24px 32px; display: flex; justify-content: space-between; align-items: flex-start; }
.header-left h1 { margin: 8px 0 4px; font-size: 1.3rem; font-weight: 700; }
.header-left p { margin: 2px 0; font-size: 0.85rem; opacity: 0.85; }
.badge { display: inline-block; background: rgba(255,255,255,0.18); border: 1px solid rgba(255,255,255,0.3); border-radius: 4px; padding: 3px 10px; font-size: 0.72rem; font-weight: 600; letter-spacing: 0.05em; margin-top: 10px; }
.kpi-row { display: flex; gap: 16px; padding: 20px 32px; background: #f9fafb; border-bottom: 1px solid #e5e7eb; }
.kpi { flex: 1; background: white; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; }
.kpi-label { font-size: 0.72rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em; color: #6b7280; margin-bottom: 4px; }
.kpi-value { font-size: 1.5rem; font-weight: 700; color: #228B22; font-variant-numeric: tabular-nums; }
.kpi-unit { font-size: 0.75rem; color: #9ca3af; margin-top: 2px; }
.content { padding: 24px 32px; }
.section-title { font-size: 0.8rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.07em; color: #228B22; margin: 24px 0 12px; border-bottom: 2px solid #228B22; padding-bottom: 6px; }
table { width: 100%; border-collapse: collapse; font-size: 0.82rem; }
th { background: #228B22; color: white; padding: 10px 14px; text-align: left; font-size: 0.75rem; font-weight: 600; letter-spacing: 0.04em; }
th:not(:first-child) { text-align: right; }
.notice { background: #fff8e1; border: 1px solid #ffc107; border-radius: 6px; padding: 12px 16px; font-size: 0.8rem; color: #7a5c00; margin: 20px 0; }
.meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 16px 0; font-size: 0.82rem; }
.meta-item { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 6px; padding: 10px 14px; }
.meta-label { font-size: 0.72rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.04em; color: #6b7280; margin-bottom: 3px; }
.footer { border-top: 1px solid #e5e7eb; padding: 16px 32px; background: #f9fafb; font-size: 0.72rem; color: #9ca3af; display: flex; justify-content: space-between; }
</style>
</head>
<body>

<!-- Header -->
<div class="header">
  <div class="header-left">
    <div>${logoHtml}</div>
    <h1>CBAM Embedded Emissions Report</h1>
    <p>Carbon Border Adjustment Mechanism — Transitional Period</p>
    <p>${data.periodLabel} &nbsp;|&nbsp; ${fmt(data.periodStart)} – ${fmt(data.periodEnd)}</p>
    <span class="badge">EU REG 2023/956 · IMPLEMENTING REG 2023/1773</span>
  </div>
  <div style="text-align:right;font-size:0.8rem;opacity:0.85;">
    <p>Prepared for: <strong>${data.orgName}</strong></p>
    ${data.declarantEori ? `<p>EORI: ${data.declarantEori}</p>` : `<p style="opacity:0.6;">EORI: not provided</p>`}
    <p>Generated: ${fmt(data.publishedAt)}</p>
    <p>By: ${data.publishedBy}</p>
  </div>
</div>

<!-- KPI row -->
<div class="kpi-row">
  <div class="kpi">
    <div class="kpi-label">Total Imported Quantity</div>
    <div class="kpi-value">${fmtN(totalQty, 1)}</div>
    <div class="kpi-unit">tonnes</div>
  </div>
  <div class="kpi">
    <div class="kpi-label">Direct Embedded CO₂e</div>
    <div class="kpi-value">${fmtN(totalDirect)}</div>
    <div class="kpi-unit">tCO₂e</div>
  </div>
  <div class="kpi">
    <div class="kpi-label">Indirect Embedded CO₂e</div>
    <div class="kpi-value">${fmtN(totalIndirect)}</div>
    <div class="kpi-unit">tCO₂e</div>
  </div>
  <div class="kpi" style="border-color:#228B22;">
    <div class="kpi-label">Total Embedded CO₂e</div>
    <div class="kpi-value">${fmtN(totalEmbedded)}</div>
    <div class="kpi-unit">tCO₂e</div>
  </div>
  <div class="kpi">
    <div class="kpi-label">Goods Items</div>
    <div class="kpi-value">${data.goodsItems.length}</div>
    <div class="kpi-unit">line items</div>
  </div>
</div>

<!-- Content -->
<div class="content">

  <div class="notice">
    ⚠️ <strong>Transitional period notice:</strong> EU CBAM reporting is mandatory for imports of covered goods from Oct 2023. No financial obligation applies until 2026. UK CBAM is expected from April 2027 — use this report as preparation. Verify country-specific default embedded emission values against the CBAM transitional registry.
  </div>

  <!-- Methodology metadata -->
  <p class="section-title">Methodology &amp; Data Sources</p>
  <div class="meta-grid">
    <div class="meta-item">
      <div class="meta-label">Emission Factor Library</div>
      <div>${data.factorLibrary}</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">Methodology Version</div>
      <div>${data.methodology} (GWP ${data.gwpVersion})</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">Reporting Standard</div>
      <div>EU Reg 2023/956 + Implementing Reg 2023/1773</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">Emission Basis</div>
      <div>Embedded CO₂e per tonne of imported goods, direct + indirect</div>
    </div>
  </div>

  <!-- Goods items table -->
  <p class="section-title">Imported Goods — Embedded Emissions Detail</p>
  ${data.goodsItems.length === 0 ? `
    <p style="color:#6b7280;font-size:0.85rem;padding:20px 0;">
      No CBAM-covered goods items found for this period. To populate this report,
      add Scope 3 purchased-goods activity records with material type metadata
      (cement, steel, aluminium) linked to non-domestic suppliers.
    </p>
  ` : `
  <table>
    <thead>
      <tr>
        <th>CN Code</th>
        <th style="min-width:160px;">Description</th>
        <th>Origin</th>
        <th>Qty (t)</th>
        <th>Direct CO₂e (t)</th>
        <th>Indirect CO₂e (t)</th>
        <th>Total CO₂e (t)</th>
        <th>Specific (t/t)</th>
        <th>Carbon £</th>
      </tr>
    </thead>
    <tbody>
      ${rowsHtml}
    </tbody>
    <tfoot>
      <tr style="background:#f0faf0;font-weight:700;">
        <td colspan="3" style="padding:10px 14px;font-size:0.82rem;">TOTAL</td>
        <td style="padding:10px 14px;text-align:right;font-variant-numeric:tabular-nums;">${fmtN(totalQty, 1)}</td>
        <td style="padding:10px 14px;text-align:right;font-variant-numeric:tabular-nums;">${fmtN(totalDirect)}</td>
        <td style="padding:10px 14px;text-align:right;font-variant-numeric:tabular-nums;">${fmtN(totalIndirect)}</td>
        <td style="padding:10px 14px;text-align:right;font-variant-numeric:tabular-nums;color:#228B22;">${fmtN(totalEmbedded)}</td>
        <td colspan="2"></td>
      </tr>
    </tfoot>
  </table>
  `}

  <p style="margin-top:24px;font-size:0.78rem;color:#6b7280;">
    This report accompanies the machine-readable CBAM XML file. Submit the XML to the EU CBAM Transitional Registry
    at <em>cbam.ec.europa.eu</em> (EU importers) or to HMRC when UK CBAM takes effect (April 2027+).
    Direct emissions = process emissions + direct energy. Indirect emissions = purchased electricity embedded in production.
    Specific embedded CO₂e = tCO₂e per tonne of imported good.
  </p>
</div>

<!-- Footer -->
<div class="footer">
  <span>${data.orgName} — CBAM Report — ${data.periodLabel}</span>
  <span>Generated ${fmt(data.publishedAt)} by ${data.publishedBy} · CarbonSite · ${data.factorLibrary}</span>
</div>

</body>
</html>`;
}
