import type { CatalogueFramework } from "./types";
import { controls, harmonizedClauses } from "./hls";

// ISO/IEC 27001:2022 with Amd 1:2024. Clause and Annex A control references
// with short control names and MetricOra's own guidance; the standard's text
// is not reproduced.

const ORG = [
  ["A.5.1", "Policies for information security", "A top-level policy and topic policies, approved, published, communicated and reviewed."],
  ["A.5.2", "Information security roles and responsibilities", "Define and allocate security roles."],
  ["A.5.3", "Segregation of duties", "Separate conflicting duties to reduce misuse."],
  ["A.5.4", "Management responsibilities", "Managers require staff to apply security in line with policy."],
  ["A.5.5", "Contact with authorities", "Keep contact with regulators, law enforcement and emergency services."],
  ["A.5.6", "Contact with special interest groups", "Keep contact with security forums and professional associations."],
  ["A.5.7", "Threat intelligence", "Collect and analyse information about threats."],
  ["A.5.8", "Information security in project management", "Build security into projects."],
  ["A.5.9", "Inventory of information and other associated assets", "Keep an inventory of information and assets with owners."],
  ["A.5.10", "Acceptable use of information and other associated assets", "Rules for acceptable use and handling."],
  ["A.5.11", "Return of assets", "Recover assets when people leave or roles change."],
  ["A.5.12", "Classification of information", "Classify information by its security needs."],
  ["A.5.13", "Labelling of information", "Label information according to the classification scheme."],
  ["A.5.14", "Information transfer", "Rules and agreements for transferring information securely."],
  ["A.5.15", "Access control", "Rules controlling physical and logical access based on business and security needs."],
  ["A.5.16", "Identity management", "Manage the full life cycle of identities."],
  ["A.5.17", "Authentication information", "Control allocation and management of passwords and other authentication information."],
  ["A.5.18", "Access rights", "Provision, review, change and remove access rights."],
  ["A.5.19", "Information security in supplier relationships", "Manage security risks from suppliers' products and services."],
  ["A.5.20", "Addressing information security within supplier agreements", "Put security requirements in supplier agreements."],
  ["A.5.21", "Managing information security in the ICT supply chain", "Manage risks in the ICT product and service supply chain."],
  ["A.5.22", "Monitoring, review and change management of supplier services", "Monitor and review supplier security and manage changes."],
  ["A.5.23", "Information security for use of cloud services", "Acquire, use, manage and exit cloud services securely."],
  ["A.5.24", "Information security incident management planning and preparation", "Plan incident management: roles, processes and communication."],
  ["A.5.25", "Assessment and decision on information security events", "Assess events and decide whether they are incidents."],
  ["A.5.26", "Response to information security incidents", "Respond to incidents according to documented procedures."],
  ["A.5.27", "Learning from information security incidents", "Use incident knowledge to strengthen controls."],
  ["A.5.28", "Collection of evidence", "Identify, collect and preserve evidence from security events."],
  ["A.5.29", "Information security during disruption", "Maintain security during disruption."],
  ["A.5.30", "ICT readiness for business continuity", "Plan, implement, maintain and test ICT readiness for continuity."],
  ["A.5.31", "Legal, statutory, regulatory and contractual requirements", "Identify and meet the legal and contractual requirements that apply to security."],
  ["A.5.32", "Intellectual property rights", "Protect intellectual property rights, including licensing."],
  ["A.5.33", "Protection of records", "Protect records from loss, destruction, falsification and unauthorised access or release."],
  ["A.5.34", "Privacy and protection of PII", "Meet privacy and personal data protection requirements."],
  ["A.5.35", "Independent review of information security", "Review the approach to security independently at planned intervals."],
  ["A.5.36", "Compliance with policies, rules and standards for information security", "Check compliance with policies and standards regularly."],
  ["A.5.37", "Documented operating procedures", "Document operating procedures and make them available."],
] as const;

const PEOPLE = [
  ["A.6.1", "Screening", "Background checks before joining, proportionate to the role and the law."],
  ["A.6.2", "Terms and conditions of employment", "Employment contracts state security responsibilities."],
  ["A.6.3", "Information security awareness, education and training", "Security awareness and training for staff, kept up to date."],
  ["A.6.4", "Disciplinary process", "A formal process for security policy breaches."],
  ["A.6.5", "Responsibilities after termination or change of employment", "Security duties that continue after leaving are defined and enforced."],
  ["A.6.6", "Confidentiality or non-disclosure agreements", "Confidentiality agreements that reflect your needs, reviewed and signed."],
  ["A.6.7", "Remote working", "Security measures for working away from the premises."],
  ["A.6.8", "Information security event reporting", "A way for staff to report observed or suspected security events promptly."],
] as const;

const PHYSICAL = [
  ["A.7.1", "Physical security perimeters", "Define and use perimeters to protect areas with information and assets."],
  ["A.7.2", "Physical entry", "Protect secure areas with entry controls."],
  ["A.7.3", "Securing offices, rooms and facilities", "Design and apply physical security for offices and facilities."],
  ["A.7.4", "Physical security monitoring", "Monitor premises for unauthorised physical access."],
  ["A.7.5", "Protecting against physical and environmental threats", "Protect against fire, flood and other physical threats."],
  ["A.7.6", "Working in secure areas", "Security measures for working in secure areas."],
  ["A.7.7", "Clear desk and clear screen", "Clear desk and clear screen rules."],
  ["A.7.8", "Equipment siting and protection", "Site equipment securely and protect it."],
  ["A.7.9", "Security of assets off-premises", "Protect assets used off site."],
  ["A.7.10", "Storage media", "Manage storage media through its life cycle."],
  ["A.7.11", "Supporting utilities", "Protect facilities from power and other utility failures."],
  ["A.7.12", "Cabling security", "Protect power and data cabling."],
  ["A.7.13", "Equipment maintenance", "Maintain equipment correctly."],
  ["A.7.14", "Secure disposal or re-use of equipment", "Remove data and licensed software before disposal or re-use."],
] as const;

const TECH = [
  ["A.8.1", "User end point devices", "Protect information on laptops, phones and other end point devices."],
  ["A.8.2", "Privileged access rights", "Restrict and manage privileged access."],
  ["A.8.3", "Information access restriction", "Restrict access to information in line with the access control policy."],
  ["A.8.4", "Access to source code", "Manage access to source code and development tools."],
  ["A.8.5", "Secure authentication", "Secure authentication technologies and procedures, such as multi-factor authentication."],
  ["A.8.6", "Capacity management", "Monitor and adjust resource use to current and expected needs."],
  ["A.8.7", "Protection against malware", "Protect against malware, supported by user awareness."],
  ["A.8.8", "Management of technical vulnerabilities", "Find, evaluate and remediate technical vulnerabilities."],
  ["A.8.9", "Configuration management", "Define, document, monitor and review secure configurations."],
  ["A.8.10", "Information deletion", "Delete information when no longer required."],
  ["A.8.11", "Data masking", "Mask data in line with access policy and legal requirements."],
  ["A.8.12", "Data leakage prevention", "Prevent sensitive information leaking from systems and networks."],
  ["A.8.13", "Information backup", "Back up information, software and systems and test restores."],
  ["A.8.14", "Redundancy of information processing facilities", "Build in enough redundancy to meet availability requirements."],
  ["A.8.15", "Logging", "Produce, protect and analyse logs of activities and events."],
  ["A.8.16", "Monitoring activities", "Monitor networks and systems for anomalous behaviour."],
  ["A.8.17", "Clock synchronization", "Synchronise system clocks to an approved source."],
  ["A.8.18", "Use of privileged utility programs", "Restrict and control utilities that can override controls."],
  ["A.8.19", "Installation of software on operational systems", "Control software installation on operational systems."],
  ["A.8.20", "Networks security", "Secure, manage and control networks and network devices."],
  ["A.8.21", "Security of network services", "Identify and monitor the security of network services."],
  ["A.8.22", "Segregation of networks", "Segregate groups of services, users and systems."],
  ["A.8.23", "Web filtering", "Manage access to external websites to reduce exposure to malicious content."],
  ["A.8.24", "Use of cryptography", "Rules for effective cryptography, including key management."],
  ["A.8.25", "Secure development life cycle", "Rules for secure development of software and systems."],
  ["A.8.26", "Application security requirements", "Identify and approve security requirements for applications."],
  ["A.8.27", "Secure system architecture and engineering principles", "Apply secure engineering principles."],
  ["A.8.28", "Secure coding", "Apply secure coding principles."],
  ["A.8.29", "Security testing in development and acceptance", "Test security during development and before acceptance."],
  ["A.8.30", "Outsourced development", "Direct, monitor and review outsourced development."],
  ["A.8.31", "Separation of development, test and production environments", "Keep environments separate and secure."],
  ["A.8.32", "Change management", "Control changes to information processing facilities and systems."],
  ["A.8.33", "Test information", "Select, protect and manage test information."],
  ["A.8.34", "Protection of information systems during audit testing", "Plan audit tests to limit disruption to operational systems."],
] as const;

export const iso27001: CatalogueFramework = {
  slug: "iso-27001-2022",
  name: "ISO/IEC 27001 Information security management systems",
  shortName: "ISO 27001",
  edition: "2022 with Amd 1:2024",
  publisher: "ISO and IEC",
  family: "information_security",
  summary: "Requirements for an information security management system: risk assessment and treatment, a Statement of Applicability and the 93 Annex A controls.",
  sourceUrl: "https://www.iso.org/standard/27001",
  contentBasis: "references",
  contentNote: "Clause and Annex A references with short control names and MetricOra's own guidance. The standard's text is not reproduced: work from your own licensed copy of ISO/IEC 27001 and 27002.",
  certifiable: true,
  tagLabels: { "annex:a": "Annex A controls only" },
  requirements: [
    ...harmonizedClauses({
      topic: "information security",
      planning: [
        { code: "6.1.2", title: "Information security risk assessment", guidance: "A defined, repeatable risk assessment process with criteria, owners and results.", evidenceHints: ["Risk assessment method", "Risk register"] },
        { code: "6.1.3", title: "Information security risk treatment", guidance: "Choose treatments, compare them with Annex A, produce a Statement of Applicability and a treatment plan approved by risk owners.", evidenceHints: ["Statement of Applicability", "Risk treatment plan"] },
      ],
      operation: [
        { code: "8.2", title: "Information security risk assessment", guidance: "Perform risk assessments at planned intervals and after significant change, and keep the results." },
        { code: "8.3", title: "Information security risk treatment", guidance: "Implement the risk treatment plan and keep the results." },
      ],
    }),
    { code: "A.5", title: "Annex A: Organizational controls" },
    ...controls("A.5", ORG, { tags: ["annex:a"] }),
    { code: "A.6", title: "Annex A: People controls" },
    ...controls("A.6", PEOPLE, { tags: ["annex:a"] }),
    { code: "A.7", title: "Annex A: Physical controls" },
    ...controls("A.7", PHYSICAL, { tags: ["annex:a"] }),
    { code: "A.8", title: "Annex A: Technological controls" },
    ...controls("A.8", TECH, { tags: ["annex:a"] }),
  ],
};
