import type { CatalogueFramework } from "./types";

// ISO 45001:2018 with Amendment 1:2024 (climate action changes to 4.1 and
// 4.2). Clause references only; titles and guidance are MetricOra's own.
export const iso45001: CatalogueFramework = {
  slug: "iso-45001-2018",
  name: "ISO 45001 Occupational health and safety management systems",
  shortName: "ISO 45001",
  edition: "2018 with Amd 1:2024",
  publisher: "International Organization for Standardization (ISO)",
  family: "management_system",
  summary:
    "Requirements for an occupational health and safety management system: consult workers, identify hazards, control risks by the hierarchy of controls, manage contractors, investigate incidents and improve.",
  sourceUrl: "https://www.iso.org/standard/63787.html",
  contentBasis: "references",
  contentNote:
    "Clause references with MetricOra's own titles and guidance. The standard's text is not reproduced: work from your own licensed copy of ISO 45001.",
  certifiable: true,
  requirements: [
    { code: "4", title: "Context of the organisation" },
    {
      code: "4.1",
      parent: "4",
      title: "Internal and external issues",
      sharedKey: "hls:4.1",
      guidance: "Record the issues that affect your ability to achieve safe and healthy workplaces. Since the 2024 amendment, decide whether climate change is a relevant issue (heat stress, flooding, severe weather on site).",
      evidenceHints: ["Context review", "Climate change relevance decision"],
    },
    {
      code: "4.2",
      parent: "4",
      title: "Workers and other interested parties",
      sharedKey: "hls:4.2",
      guidance: "Identify workers and other interested parties, their needs and expectations, and which become legal or other requirements.",
      evidenceHints: ["Interested parties register"],
    },
    { code: "4.3", parent: "4", title: "Scope of the management system", sharedKey: "hls:4.3", guidance: "Define the activities, sites and work under your control that the system covers.", evidenceHints: ["Scope statement"] },
    { code: "4.4", parent: "4", title: "The OH&S management system", sharedKey: "hls:4.4", guidance: "Show the processes of the system and how they interact.", evidenceHints: ["Manual or process map"] },
    { code: "5", title: "Leadership and worker participation" },
    {
      code: "5.1",
      parent: "5",
      title: "Leadership and commitment",
      sharedKey: "hls:5.1",
      guidance: "Top management takes overall responsibility for preventing work-related injury and ill health, protects workers who report incidents and hazards, and supports safety committees.",
      evidenceHints: ["Director site visits", "Board minutes"],
    },
    {
      code: "5.2",
      parent: "5",
      title: "OH&S policy",
      sharedKey: "hls:5.2",
      guidance: "A signed policy committing to safe and healthy working conditions, meeting legal requirements, eliminating hazards and reducing risks, continual improvement, and consultation and participation of workers.",
      evidenceHints: ["Signed health and safety policy"],
    },
    { code: "5.3", parent: "5", title: "Roles, responsibilities and authorities", sharedKey: "hls:5.3", guidance: "Assign and communicate responsibilities at every level, including who reports on OH&S performance.", evidenceHints: ["Organisation chart", "Appointment letters"], signals: ["members"] },
    {
      code: "5.4",
      parent: "5",
      title: "Consultation and participation of workers",
      guidance: "Consult workers (and their representatives) and involve non-managerial workers in hazard identification, incident investigation and deciding controls. Remove barriers such as fear of reprisal.",
      evidenceHints: ["Safety committee minutes", "Worker consultation records", "Near-miss reports from the field"],
      signals: ["hs_incidents"],
    },
    { code: "6", title: "Planning" },
    { code: "6.1", parent: "6", title: "Actions to address risks and opportunities" },
    { code: "6.1.1", parent: "6.1", title: "General", sharedKey: "hls:6.1", guidance: "Plan for the risks and opportunities of the system, including planned changes." },
    { code: "6.1.2", parent: "6.1", title: "Hazard identification and assessment of risks and opportunities" },
    {
      code: "6.1.2.1",
      parent: "6.1.2",
      title: "Hazard identification",
      guidance: "Identify hazards on an ongoing basis: routine and non-routine work, human factors, emergencies, people and places affected, changes and past incidents.",
      evidenceHints: ["Hazard register", "Risk assessments", "RAMS"],
      signals: ["method_statements"],
    },
    {
      code: "6.1.2.2",
      parent: "6.1.2",
      title: "Assessing OH&S and other risks",
      guidance: "Assess the risks from identified hazards with a defined method, and the other risks to the system itself.",
      evidenceHints: ["Risk assessment method", "Scored risk register"],
      signals: ["method_statements"],
    },
    { code: "6.1.2.3", parent: "6.1.2", title: "Assessing OH&S and other opportunities", guidance: "Look for opportunities to improve safety performance, for example adapting work to workers.", evidenceHints: ["Opportunities in the register"] },
    {
      code: "6.1.3",
      parent: "6.1",
      title: "Legal and other requirements",
      guidance: "Identify and keep up to date the legal and other requirements that apply to your hazards and risks (e.g. CDM 2015, RIDDOR, COSHH, Work at Height) and how they apply.",
      evidenceHints: ["Legal register"],
      signals: ["legal_register"],
    },
    { code: "6.1.4", parent: "6.1", title: "Planning action", guidance: "Plan actions for risks, opportunities, legal requirements and emergencies, and how to check they worked.", evidenceHints: ["Action plan"] },
    { code: "6.2", parent: "6", title: "OH&S objectives" },
    { code: "6.2.1", parent: "6.2", title: "Setting OH&S objectives", sharedKey: "hls:6.2", guidance: "Set measurable objectives consistent with the policy, considering consultation results.", evidenceHints: ["Objectives with targets"] },
    { code: "6.2.2", parent: "6.2", title: "Plans to achieve objectives", guidance: "Actions, resources, owners, dates and how results are evaluated for each objective.", evidenceHints: ["Objective action plans"] },
    { code: "7", title: "Support" },
    { code: "7.1", parent: "7", title: "Resources", sharedKey: "hls:7.1", guidance: "Provide the resources the system needs.", evidenceHints: ["Budget or resource plan"] },
    { code: "7.2", parent: "7", title: "Competence", sharedKey: "hls:7.2", guidance: "Workers are competent, including in hazard identification, with records of training and qualifications (e.g. CSCS, SMSTS, SSSTS).", evidenceHints: ["Training matrix", "Card checks"] },
    {
      code: "7.3",
      parent: "7",
      title: "Awareness",
      sharedKey: "hls:7.3",
      guidance: "Workers know the policy, hazards and risks relevant to them, incidents and their outcomes, and that they can remove themselves from imminent danger.",
      evidenceHints: ["Inductions", "Toolbox talks", "Safety alerts"],
    },
    { code: "7.4", parent: "7", title: "Communication", sharedKey: "hls:7.4" },
    { code: "7.4.1", parent: "7.4", title: "Communication process", guidance: "Decide what is communicated, when, to whom and how, considering diversity such as language and literacy." },
    { code: "7.4.2", parent: "7.4", title: "Internal communication", guidance: "Communicate across levels and to contractors and visitors on site.", evidenceHints: ["Site briefings", "Notice boards"] },
    { code: "7.4.3", parent: "7.4", title: "External communication", guidance: "Communicate externally as legal requirements demand, e.g. RIDDOR reports to the HSE.", evidenceHints: ["RIDDOR submissions"], signals: ["hs_incidents"] },
    { code: "7.5", parent: "7", title: "Documented information", sharedKey: "hls:7.5" },
    { code: "7.5.1", parent: "7.5", title: "What must be documented", guidance: "Keep the documents the standard requires and those your system needs." },
    { code: "7.5.2", parent: "7.5", title: "Creating and updating documents", guidance: "Documents are identified, reviewed and approved." },
    { code: "7.5.3", parent: "7.5", title: "Control of documented information", guidance: "Documents are available, protected, version-controlled and retained.", signals: ["evidence_files"] },
    { code: "8", title: "Operation" },
    { code: "8.1", parent: "8", title: "Operational planning and control", sharedKey: "hls:8.1" },
    {
      code: "8.1.1",
      parent: "8.1",
      title: "General",
      guidance: "Plan and control the processes that meet OH&S requirements: safe systems of work, permits to work, and adapting work to workers.",
      evidenceHints: ["Safe systems of work", "Permits to work"],
      signals: ["method_statements"],
    },
    {
      code: "8.1.2",
      parent: "8.1",
      title: "Eliminating hazards and reducing risks",
      guidance: "Apply the hierarchy of controls: eliminate, substitute, engineering controls, administrative controls, then PPE.",
      evidenceHints: ["Risk assessments showing the hierarchy applied"],
      signals: ["method_statements"],
    },
    { code: "8.1.3", parent: "8.1", title: "Management of change", guidance: "Assess the OH&S effect of planned changes (new work, equipment, legal changes) before they happen.", evidenceHints: ["Change assessments"] },
    { code: "8.1.4", parent: "8.1", title: "Procurement" },
    { code: "8.1.4.1", parent: "8.1.4", title: "General", guidance: "Procurement of products and services meets your OH&S requirements.", evidenceHints: ["Procurement checklist"], signals: ["suppliers"] },
    {
      code: "8.1.4.2",
      parent: "8.1.4",
      title: "Contractors",
      guidance: "Coordinate with contractors: identify hazards from their work, set OH&S criteria for selecting them and check they meet your requirements on site.",
      evidenceHints: ["Subcontractor prequalification (e.g. CHAS, SSIP)", "Contractor RAMS reviews", "Site audits"],
      signals: ["suppliers", "method_statements"],
    },
    { code: "8.1.4.3", parent: "8.1.4", title: "Outsourcing", guidance: "Outsourced functions and processes are controlled.", evidenceHints: ["Outsourcing agreements"] },
    {
      code: "8.2",
      parent: "8",
      title: "Emergency preparedness and response",
      guidance: "Plan responses to emergencies, including first aid, train people, test the plans and review them after tests and incidents.",
      evidenceHints: ["Emergency plans", "Fire drill records", "First aid provision"],
      signals: ["hs_incidents"],
    },
    { code: "9", title: "Performance evaluation" },
    { code: "9.1", parent: "9", title: "Monitoring, measurement, analysis and evaluation", sharedKey: "hls:9.1" },
    {
      code: "9.1.1",
      parent: "9.1",
      title: "Monitoring and measurement",
      guidance: "Monitor legal compliance, activities and operations, progress on objectives and the effectiveness of controls, with calibrated equipment where relevant.",
      evidenceHints: ["Accident and incident rates", "Inspection records", "Calibration records"],
      signals: ["hs_incidents"],
    },
    { code: "9.1.2", parent: "9.1", title: "Evaluation of compliance", guidance: "Evaluate compliance with legal and other requirements at set intervals and act on gaps.", evidenceHints: ["Compliance evaluation records"], signals: ["legal_register"] },
    { code: "9.2", parent: "9", title: "Internal audit", sharedKey: "hls:9.2" },
    { code: "9.2.1", parent: "9.2", title: "Audit purpose", guidance: "Audit at planned intervals whether the system conforms and is effective." },
    { code: "9.2.2", parent: "9.2", title: "Audit programme", guidance: "Plan audits, use objective auditors, report results to management and to workers.", evidenceHints: ["Audit programme", "Audit reports"] },
    {
      code: "9.3",
      parent: "9",
      title: "Management review",
      sharedKey: "hls:9.3",
      guidance: "Top management reviews the system, including incidents, consultation results, risks and opportunities, and communicates the outputs to workers.",
      evidenceHints: ["Management review minutes"],
    },
    { code: "10", title: "Improvement" },
    { code: "10.1", parent: "10", title: "General", sharedKey: "hls:10.1", guidance: "Identify opportunities for improvement and act on them." },
    {
      code: "10.2",
      parent: "10",
      title: "Incident, nonconformity and corrective action",
      sharedKey: "hls:10.2",
      guidance: "Report and investigate incidents promptly with workers involved, find root causes, act by the hierarchy of controls and check effectiveness.",
      evidenceHints: ["Incident investigations", "Corrective action log", "RIDDOR records"],
      signals: ["hs_incidents"],
    },
    { code: "10.3", parent: "10", title: "Continual improvement", sharedKey: "hls:10.3", guidance: "Improve OH&S performance and promote a positive safety culture.", evidenceHints: ["Trend in incident rates"], signals: ["hs_incidents"] },
  ],
};
