import { iso9001 } from "./iso-9001-2015";
import { revise } from "./revise";

// ISO 9001:2026, published 16 September 2026, replacing ISO 9001:2015 and its
// 2024 climate amendment. Built from the 2015 catalogue; the changes below
// come from certification body and consultancy notes (editionSources), not
// from the standard's text. Clause references with MetricOra's own titles and
// guidance only; check them against your licensed copy.
export const iso9001_2026 = revise({
  base: iso9001,
  meta: {
    slug: "iso-9001-2026",
    name: "ISO 9001 Quality management systems",
    shortName: "ISO 9001:2026",
    edition: "2026",
    summary:
      "The 2026 edition of the quality management system standard: the 2015 system on ISO's harmonized structure, with quality culture and ethical behaviour, risks and opportunities treated separately, planned changes, organisational knowledge and the climate change amendment built in.",
    sourceUrl: "https://www.iso.org/iso-9001-quality-management.html",
    contentNote:
      "Clause references with MetricOra's own titles and guidance, built from the 2015 edition and published notes on the 2026 changes. The standard's text is not reproduced: work from your own licensed copy of ISO 9001:2026 and check the clause titles against it.",
    editionSources: [
      { label: "NSF: ISO 9001:2026 published on 16 September 2026", url: "https://www.nsf.org/knowledge-library/iso-90012026-published-on-september-16-2026-what-quality-leaders-need-to-know" },
      { label: "TÜV SÜD: key things to know about the revision", url: "https://www.tuvsud.com/en-us/knowledge-hub/articles/iso-9001-everything-you-need-to-know-about-the-new-revision" },
      { label: "BSI: ISO 9001:2026 key changes and guidance", url: "https://www.bsigroup.com/en-IE/products-and-services/standards-services/iso-9001-2026-key-changes-and-guidance/" },
      { label: "9001 Simplified: ISO 9001:2026 changes explained", url: "https://www.9001simplified.com/learn/iso-9001-2026-changes.php" },
    ],
  },
  remove: ["10.3"],
  set: [
    {
      code: "4.1",
      parent: "4",
      title: "Internal and external issues",
      sharedKey: "hls:4.1",
      guidance: "Record the issues relevant to delivering quality, including whether climate change is relevant; the 2024 amendment is now part of the requirements.",
      evidenceHints: ["Context review", "Climate change relevance decision"],
      editionChange: { kind: "changed", note: "Climate change consideration is in the requirement itself rather than an amendment." },
    },
    {
      code: "4.2",
      parent: "4",
      title: "Interested parties and their requirements",
      sharedKey: "hls:4.2",
      guidance: "Identify interested parties and their relevant requirements, and decide which of those requirements the quality management system will address.",
      evidenceHints: ["Interested parties register with the requirements adopted"],
      editionChange: { kind: "changed", note: "Explicitly decide which interested party requirements the system addresses." },
    },
    {
      code: "5.1",
      parent: "5",
      title: "Leadership and commitment",
      sharedKey: "hls:5.1",
      guidance:
        "Top management is accountable for the system, keeps the focus on customers, and promotes a quality culture and ethical behaviour. Expect auditors to ask how leaders show this, for example in briefings, recognition and how concerns are handled.",
      evidenceHints: ["Board minutes", "Code of conduct or ethics statement", "Quality culture initiatives"],
      editionChange: { kind: "changed", note: "Promoting quality culture and ethical behaviour is added to leadership and commitment (5.1.1)." },
    },
    { code: "6.1", parent: "6", title: "Actions to address risks and opportunities", editionChange: { kind: "changed", note: "Split into 6.1.1 General, 6.1.2 risks and 6.1.3 opportunities." } },
    {
      code: "6.1.1",
      parent: "6.1",
      title: "General",
      after: "6.1",
      sharedKey: "hls:6.1",
      guidance: "Determine the risks and opportunities from your issues (4.1) and interested parties (4.2) that need addressing, with analysis and evaluation proportionate to their effect on conformity and customer satisfaction.",
      evidenceHints: ["Risk and opportunity register"],
      editionChange: { kind: "renumbered", from: ["6.1"], note: "Was part of 6.1." },
    },
    {
      code: "6.1.2",
      parent: "6.1",
      title: "Actions to address risks",
      after: "6.1.1",
      guidance: "Plan and take action on the risks you decided to address, integrate the actions into your processes and check they worked.",
      evidenceHints: ["Risk treatment actions"],
      editionChange: { kind: "changed", from: ["6.1"], note: "Risks now have their own sub-clause." },
    },
    {
      code: "6.1.3",
      parent: "6.1",
      title: "Actions to address opportunities",
      after: "6.1.2",
      guidance: "Plan and take action on the opportunities you decided to pursue, such as new services, technology or ways of working, and evaluate the results.",
      evidenceHints: ["Opportunities with owners and actions"],
      editionChange: { kind: "new", from: ["6.1"], note: "Opportunities are treated separately from risks, and leadership is expected to promote them." },
    },
    {
      code: "6.3",
      parent: "6",
      title: "Planning of changes",
      guidance: "Plan changes to the quality management system: purpose and consequences, keeping the system intact, resources and responsibilities, so intended results are still achieved.",
      evidenceHints: ["Change records", "Management of change reviews"],
      editionChange: { kind: "changed", note: "Requirements for changes to the system are reinforced." },
    },
    {
      code: "7.1",
      parent: "7",
      title: "Resources",
      sharedKey: "hls:7.1",
      guidance:
        "People, infrastructure, work environment, monitoring and measuring resources (with calibration traceability) and organisational knowledge. The 2026 edition broadens knowledge (7.1.6) to the know-how needed to achieve intended results, and keeping, applying and sharing it; the work environment (7.1.4) refers to quality culture.",
      evidenceHints: ["Equipment and calibration register", "Lessons learned and knowledge records"],
      editionChange: { kind: "changed", note: "Organisational knowledge broadened (7.1.6); quality culture referenced in the work environment (7.1.4)." },
    },
    {
      code: "7.3",
      parent: "7",
      title: "Awareness",
      sharedKey: "hls:7.3",
      guidance: "People know the quality policy, relevant objectives, their contribution, the implications of not conforming, and the organisation's quality culture and expected ethical behaviour.",
      evidenceHints: ["Inductions", "Toolbox talks covering conduct and quality culture"],
      editionChange: { kind: "changed", note: "Awareness of quality culture and ethical behaviour added." },
    },
    {
      code: "8.2",
      parent: "8",
      title: "Requirements for products and services",
      guidance: "Communicate with customers, including relevant contingency actions (8.2.1), determine and review requirements before committing, and control changes to them.",
      evidenceHints: ["Contract review records", "Tender reviews", "Customer contingency communications"],
      editionChange: { kind: "changed", note: "Customer communication includes relevant contingency actions (8.2.1)." },
    },
    {
      code: "8.3",
      parent: "8",
      title: "Design and development",
      guidance: "Plan, control, verify and validate design work, including involving customers where relevant and defining what the completed design must provide (8.3.2, 8.3.5). May be excluded from scope when you do no design, with justification.",
      evidenceHints: ["Design reviews", "Design outputs", "Design change records"],
      editionChange: { kind: "changed", note: "Design planning and outputs clarified (8.3.2, 8.3.5)." },
    },
    { code: "9.3", parent: "9", title: "Management review", editionChange: { kind: "changed", note: "Split into 9.3.1 General, 9.3.2 Inputs and 9.3.3 Results." } },
    {
      code: "9.3.1",
      parent: "9.3",
      title: "General",
      after: "9.3",
      sharedKey: "hls:9.3",
      guidance: "Top management reviews the quality management system at planned intervals.",
      evidenceHints: ["Management review schedule"],
      editionChange: { kind: "renumbered", from: ["9.3"], note: "Was part of 9.3." },
    },
    {
      code: "9.3.2",
      parent: "9.3",
      title: "Management review inputs",
      after: "9.3.1",
      guidance: "Cover the required inputs, including changes in interested parties' relevant needs and expectations, customer satisfaction, objectives, process performance, nonconformities, audit results, supplier performance, resources and risks and opportunities.",
      evidenceHints: ["Management review agenda and inputs"],
      editionChange: { kind: "renumbered", from: ["9.3"], note: "Was part of 9.3; interested parties' changing needs named as an input." },
    },
    {
      code: "9.3.3",
      parent: "9.3",
      title: "Management review results",
      after: "9.3.2",
      guidance: "Record decisions and actions on improvement, changes to the system and resources.",
      evidenceHints: ["Management review minutes with decisions and actions"],
      editionChange: { kind: "renumbered", from: ["9.3"], note: "Was part of 9.3." },
    },
    {
      code: "10.1",
      parent: "10",
      title: "Continual improvement",
      sharedKey: "hls:10.3",
      guidance: "Improve products, services and the system, using analysis and management review outputs; keep improvement activities that already work.",
      evidenceHints: ["Improvement plan", "Trend of quality KPIs"],
      editionChange: { kind: "renumbered", from: ["10.1", "10.3"], note: "2015's 10.1 General and 10.3 Continual improvement are consolidated in 10.1." },
    },
  ],
});
