import type { CatalogueFramework } from "./types";

// ISO 14001:2015 with Amendment 1:2024 (climate action changes to 4.1 and
// 4.2). Clause references only; titles and guidance are MetricOra's own.
export const iso14001: CatalogueFramework = {
  slug: "iso-14001-2015",
  name: "ISO 14001 Environmental management systems",
  shortName: "ISO 14001",
  edition: "2015 with Amd 1:2024",
  publisher: "International Organization for Standardization (ISO)",
  family: "management_system",
  summary:
    "Requirements for an environmental management system: know your environmental aspects and legal obligations, control them, set objectives, check performance and improve.",
  sourceUrl: "https://www.iso.org/standard/60857.html",
  contentBasis: "references",
  contentNote:
    "Clause references with MetricOra's own titles and guidance. The standard's text is not reproduced: work from your own licensed copy of ISO 14001.",
  certifiable: true,
  requirements: [
    { code: "4", title: "Context of the organisation" },
    {
      code: "4.1",
      parent: "4",
      title: "Internal and external issues",
      sharedKey: "hls:4.1",
      guidance:
        "Record the internal and external issues that affect what your environmental management system can achieve, including environmental conditions that affect you. Since the 2024 amendment you must also decide whether climate change is a relevant issue.",
      evidenceHints: ["Context or SWOT/PESTLE review", "Minutes where the issues were agreed", "Climate change relevance decision"],
    },
    {
      code: "4.2",
      parent: "4",
      title: "Interested parties and their needs",
      sharedKey: "hls:4.2",
      guidance:
        "List the interested parties (clients, regulators, neighbours, workers, supply chain) and which of their needs become compliance obligations. The 2024 amendment notes that they may have climate change requirements.",
      evidenceHints: ["Interested parties register", "Client and framework requirements, such as a Carbon Reduction Plan"],
    },
    {
      code: "4.3",
      parent: "4",
      title: "Scope of the management system",
      sharedKey: "hls:4.3",
      guidance: "Write down the boundaries: sites, activities, products and services covered, and justify anything left out.",
      evidenceHints: ["Scope statement", "Certificate scope wording"],
    },
    {
      code: "4.4",
      parent: "4",
      title: "The environmental management system",
      sharedKey: "hls:4.4",
      guidance: "Show the system exists and is maintained: processes, how they interact, and how the knowledge from 4.1 and 4.2 feeds them.",
      evidenceHints: ["Manual or process map"],
    },
    { code: "5", title: "Leadership" },
    {
      code: "5.1",
      parent: "5",
      title: "Leadership and commitment",
      sharedKey: "hls:5.1",
      guidance: "Top management takes accountability for the system, provides resources and makes environmental management part of how the business runs.",
      evidenceHints: ["Board or director minutes", "Management review records"],
    },
    {
      code: "5.2",
      parent: "5",
      title: "Environmental policy",
      sharedKey: "hls:5.2",
      guidance:
        "A signed policy that commits to protecting the environment (including preventing pollution), meeting compliance obligations and continual improvement, communicated to staff and available to interested parties.",
      evidenceHints: ["Signed environmental policy", "Where it is published"],
    },
    {
      code: "5.3",
      parent: "5",
      title: "Roles, responsibilities and authorities",
      sharedKey: "hls:5.3",
      guidance: "Named people responsible for the system and for reporting its performance to top management.",
      evidenceHints: ["Organisation chart", "Role descriptions"],
      signals: ["members"],
    },
    { code: "6", title: "Planning" },
    { code: "6.1", parent: "6", title: "Actions to address risks and opportunities" },
    {
      code: "6.1.1",
      parent: "6.1",
      title: "Risks and opportunities",
      sharedKey: "hls:6.1",
      guidance:
        "Identify the risks and opportunities that come from your issues, interested parties, aspects and obligations, including potential emergencies.",
      evidenceHints: ["Risk and opportunity register"],
    },
    {
      code: "6.1.2",
      parent: "6.1",
      title: "Environmental aspects",
      guidance:
        "Keep a register of the environmental aspects of your activities and their impacts, taking a life cycle perspective, covering normal, abnormal and emergency conditions, and decide which are significant.",
      evidenceHints: ["Aspects and impacts register with significance criteria"],
      signals: ["environmental_aspects"],
    },
    {
      code: "6.1.3",
      parent: "6.1",
      title: "Compliance obligations",
      guidance:
        "Identify the legal and other requirements that apply to your aspects (permits, waste duty of care, client requirements) and how they apply to you.",
      evidenceHints: ["Legal register", "Permits and exemptions"],
      signals: ["legal_register", "environmental_permits"],
    },
    {
      code: "6.1.4",
      parent: "6.1",
      title: "Planning action",
      guidance: "Plan how you will act on significant aspects, obligations and risks, and how you will check the actions worked.",
      evidenceHints: ["Action plan", "Operational controls linked to significant aspects"],
    },
    { code: "6.2", parent: "6", title: "Environmental objectives" },
    {
      code: "6.2.1",
      parent: "6.2",
      title: "Setting environmental objectives",
      sharedKey: "hls:6.2",
      guidance: "Set measurable objectives consistent with the policy, taking significant aspects and obligations into account.",
      evidenceHints: ["Objectives with targets and dates"],
      signals: ["reduction_targets"],
    },
    {
      code: "6.2.2",
      parent: "6.2",
      title: "Plans to achieve objectives",
      guidance: "For each objective: what will be done, resources, who is responsible, when, and how results will be evaluated.",
      evidenceHints: ["Objective action plans", "Carbon Reduction Plan measures"],
      signals: ["reduction_targets"],
    },
    { code: "7", title: "Support" },
    { code: "7.1", parent: "7", title: "Resources", sharedKey: "hls:7.1", guidance: "Show the system has the people, equipment and budget it needs.", evidenceHints: ["Budget or resource plan"] },
    {
      code: "7.2",
      parent: "7",
      title: "Competence",
      sharedKey: "hls:7.2",
      guidance: "People whose work affects environmental performance are competent, with training records to show it.",
      evidenceHints: ["Training matrix", "Toolbox talk records", "Qualifications"],
    },
    {
      code: "7.3",
      parent: "7",
      title: "Awareness",
      sharedKey: "hls:7.3",
      guidance: "Workers know the policy, the significant aspects that relate to their work and what happens if they do not follow requirements.",
      evidenceHints: ["Site inductions", "Toolbox talks"],
    },
    { code: "7.4", parent: "7", title: "Communication", sharedKey: "hls:7.4" },
    { code: "7.4.1", parent: "7.4", title: "Communication process", guidance: "Decide what you communicate, when, to whom and how, internally and externally.", evidenceHints: ["Communication plan"] },
    { code: "7.4.2", parent: "7.4", title: "Internal communication", guidance: "Share environmental information across levels and functions, and let workers suggest improvements.", evidenceHints: ["Briefings", "Suggestion records"] },
    {
      code: "7.4.3",
      parent: "7.4",
      title: "External communication",
      guidance: "Communicate externally as your obligations require, for example to regulators, clients and neighbours.",
      evidenceHints: ["Published reports", "Regulator correspondence", "Complaint log"],
    },
    { code: "7.5", parent: "7", title: "Documented information", sharedKey: "hls:7.5" },
    { code: "7.5.1", parent: "7.5", title: "What must be documented", guidance: "Keep the documents the standard requires and those you need for the system to work." },
    { code: "7.5.2", parent: "7.5", title: "Creating and updating documents", guidance: "Documents are identified, reviewed and approved before use.", evidenceHints: ["Document register with versions"] },
    {
      code: "7.5.3",
      parent: "7.5",
      title: "Control of documented information",
      guidance: "Documents are available where needed, protected, version-controlled, retained and disposed of properly.",
      evidenceHints: ["Document control procedure", "Retention schedule"],
      signals: ["evidence_files"],
    },
    { code: "8", title: "Operation" },
    {
      code: "8.1",
      parent: "8",
      title: "Operational planning and control",
      sharedKey: "hls:8.1",
      guidance:
        "Control the processes linked to significant aspects: method statements, permits, pollution prevention, waste management, and environmental requirements passed to contractors and suppliers, with a life cycle view.",
      evidenceHints: ["Approved method statements", "Site environmental plans", "Subcontractor requirements"],
      signals: ["method_statements", "environmental_permits", "suppliers"],
    },
    {
      code: "8.2",
      parent: "8",
      title: "Emergency preparedness and response",
      guidance: "Plan for potential environmental emergencies such as spills, test the plans periodically and review them after incidents and tests.",
      evidenceHints: ["Spill response plans", "Drill records", "Incident reviews"],
      signals: ["environmental_incidents"],
    },
    { code: "9", title: "Performance evaluation" },
    { code: "9.1", parent: "9", title: "Monitoring, measurement, analysis and evaluation", sharedKey: "hls:9.1" },
    {
      code: "9.1.1",
      parent: "9.1",
      title: "Monitoring and measurement",
      guidance: "Decide what you measure (energy, emissions, waste, water, incidents), how and how often, and evaluate environmental performance.",
      evidenceHints: ["Monitoring plan", "Emissions inventory", "Waste and water records", "Calibration records"],
      signals: ["emissions_monitoring", "waste_water_monitoring"],
    },
    {
      code: "9.1.2",
      parent: "9.1",
      title: "Evaluation of compliance",
      guidance: "Check compliance with each obligation at a set frequency, act on any gap and keep the results.",
      evidenceHints: ["Compliance evaluation records against the legal register"],
      signals: ["legal_register", "environmental_permits"],
    },
    { code: "9.2", parent: "9", title: "Internal audit", sharedKey: "hls:9.2" },
    { code: "9.2.1", parent: "9.2", title: "Audit purpose", guidance: "Audit at planned intervals whether the system meets your own requirements and the standard, and is effective." },
    {
      code: "9.2.2",
      parent: "9.2",
      title: "Audit programme",
      guidance: "A programme with frequency, methods, responsibilities and reporting; objective auditors; results reported to management.",
      evidenceHints: ["Audit programme", "Audit reports"],
    },
    {
      code: "9.3",
      parent: "9",
      title: "Management review",
      sharedKey: "hls:9.3",
      guidance:
        "Top management reviews the system at planned intervals, covering the set inputs (issues, obligations, aspects, objectives, performance, audits, resources, complaints) and records decisions.",
      evidenceHints: ["Management review minutes with decisions and actions"],
    },
    { code: "10", title: "Improvement" },
    { code: "10.1", parent: "10", title: "General", sharedKey: "hls:10.1", guidance: "Identify opportunities for improvement and act on them." },
    {
      code: "10.2",
      parent: "10",
      title: "Nonconformity and corrective action",
      sharedKey: "hls:10.2",
      guidance: "React to nonconformities, deal with consequences, find root causes, act to prevent recurrence and check the action worked.",
      evidenceHints: ["Corrective action log", "Incident investigations"],
      signals: ["environmental_incidents"],
    },
    { code: "10.3", parent: "10", title: "Continual improvement", sharedKey: "hls:10.3", guidance: "Show environmental performance and the system improve over time.", evidenceHints: ["Year-on-year performance trends"], signals: ["emissions_monitoring"] },
  ],
};
