import type { CatalogueFramework } from "./types";

// ISO 9001:2015 with Amendment 1:2024 (climate action changes to 4.1 and
// 4.2). Clause references only; titles and guidance are MetricOra's own.
export const iso9001: CatalogueFramework = {
  slug: "iso-9001-2015",
  name: "ISO 9001 Quality management systems",
  shortName: "ISO 9001",
  edition: "2015 with Amd 1:2024",
  publisher: "International Organization for Standardization (ISO)",
  family: "management_system",
  summary:
    "Requirements for a quality management system: understand customer requirements, control how work is planned, delivered and checked, and improve customer satisfaction.",
  sourceUrl: "https://www.iso.org/standard/62085.html",
  contentBasis: "references",
  contentNote:
    "Clause references with MetricOra's own titles and guidance. The standard's text is not reproduced: work from your own licensed copy of ISO 9001.",
  certifiable: true,
  requirements: [
    { code: "4", title: "Context of the organisation" },
    { code: "4.1", parent: "4", title: "Internal and external issues", sharedKey: "hls:4.1", guidance: "Record the issues relevant to delivering quality, and (since the 2024 amendment) whether climate change is relevant.", evidenceHints: ["Context review"] },
    { code: "4.2", parent: "4", title: "Interested parties and their requirements", sharedKey: "hls:4.2", guidance: "Identify interested parties relevant to the system and their requirements.", evidenceHints: ["Interested parties register"] },
    { code: "4.3", parent: "4", title: "Scope of the management system", sharedKey: "hls:4.3", guidance: "Define the scope, and justify any requirement you say does not apply (for example design, 8.3).", evidenceHints: ["Scope statement"] },
    { code: "4.4", parent: "4", title: "The quality management system and its processes", sharedKey: "hls:4.4", guidance: "Determine the processes, their inputs, outputs, sequence, owners, measures and risks.", evidenceHints: ["Process map"] },
    { code: "5", title: "Leadership" },
    { code: "5.1", parent: "5", title: "Leadership and commitment", sharedKey: "hls:5.1", guidance: "Top management is accountable for the system, and keeps the focus on customers and on risks and opportunities.", evidenceHints: ["Board minutes"] },
    { code: "5.2", parent: "5", title: "Quality policy", sharedKey: "hls:5.2", guidance: "A policy that suits the business, gives a framework for objectives and commits to meeting requirements and improving; communicated and available.", evidenceHints: ["Signed quality policy"] },
    { code: "5.3", parent: "5", title: "Roles, responsibilities and authorities", sharedKey: "hls:5.3", guidance: "Assign and communicate responsibilities for the system.", evidenceHints: ["Organisation chart"], signals: ["members"] },
    { code: "6", title: "Planning" },
    { code: "6.1", parent: "6", title: "Actions to address risks and opportunities", sharedKey: "hls:6.1", guidance: "Plan actions on the risks and opportunities from 4.1 and 4.2, proportionate to their effect on product and service conformity.", evidenceHints: ["Risk and opportunity register"] },
    { code: "6.2", parent: "6", title: "Quality objectives and planning to achieve them", sharedKey: "hls:6.2", guidance: "Measurable objectives with actions, resources, owners, dates and how results are evaluated.", evidenceHints: ["Quality objectives"] },
    { code: "6.3", parent: "6", title: "Planning of changes", guidance: "Changes to the system are carried out in a planned way.", evidenceHints: ["Change records"] },
    { code: "7", title: "Support" },
    { code: "7.1", parent: "7", title: "Resources", sharedKey: "hls:7.1", guidance: "People, infrastructure, work environment, monitoring and measuring resources (with calibration traceability) and organisational knowledge.", evidenceHints: ["Equipment and calibration register", "Knowledge records"] },
    { code: "7.2", parent: "7", title: "Competence", sharedKey: "hls:7.2", guidance: "People are competent, with evidence.", evidenceHints: ["Training matrix"] },
    { code: "7.3", parent: "7", title: "Awareness", sharedKey: "hls:7.3", guidance: "People know the policy, relevant objectives and their contribution.", evidenceHints: ["Inductions"] },
    { code: "7.4", parent: "7", title: "Communication", sharedKey: "hls:7.4", guidance: "Decide internal and external communications: what, when, with whom, how and by whom.", evidenceHints: ["Communication plan"] },
    { code: "7.5", parent: "7", title: "Documented information", sharedKey: "hls:7.5", guidance: "Control the documents and records the system needs: identification, review, approval, versions, retention.", evidenceHints: ["Document register"], signals: ["evidence_files"] },
    { code: "8", title: "Operation" },
    { code: "8.1", parent: "8", title: "Operational planning and control", sharedKey: "hls:8.1", guidance: "Plan the processes needed to deliver products and services: criteria, resources, controls and records.", evidenceHints: ["Project quality plans", "Inspection and test plans"], signals: ["method_statements"] },
    { code: "8.2", parent: "8", title: "Requirements for products and services", guidance: "Communicate with customers, determine and review requirements before committing, and control changes to them.", evidenceHints: ["Contract review records", "Tender reviews"] },
    { code: "8.3", parent: "8", title: "Design and development", guidance: "Plan, control, verify and validate design work, including changes. May be excluded from scope when you do no design, with justification.", evidenceHints: ["Design reviews", "Design change records"] },
    {
      code: "8.4",
      parent: "8",
      title: "Control of externally provided processes, products and services",
      guidance: "Select, evaluate and monitor suppliers and subcontractors, and tell them your requirements.",
      evidenceHints: ["Approved supplier list", "Supplier evaluations"],
      signals: ["suppliers"],
    },
    { code: "8.5", parent: "8", title: "Production and service provision", guidance: "Deliver under controlled conditions, with identification and traceability, care of customer property, preservation, post-delivery activities and control of changes.", evidenceHints: ["Site records", "Handover documentation"] },
    { code: "8.6", parent: "8", title: "Release of products and services", guidance: "Verify requirements are met before release, with records of who authorised it.", evidenceHints: ["Inspection sign-offs", "Completion certificates"] },
    { code: "8.7", parent: "8", title: "Control of nonconforming outputs", guidance: "Identify and control outputs that do not conform, and record what was done.", evidenceHints: ["Nonconformance reports", "Snagging logs"] },
    { code: "9", title: "Performance evaluation" },
    { code: "9.1", parent: "9", title: "Monitoring, measurement, analysis and evaluation", sharedKey: "hls:9.1", guidance: "Measure what matters, monitor customer satisfaction and analyse the data to evaluate performance.", evidenceHints: ["KPI reports", "Customer feedback"] },
    { code: "9.2", parent: "9", title: "Internal audit", sharedKey: "hls:9.2", guidance: "Plan and carry out internal audits with objective auditors and report results.", evidenceHints: ["Audit programme", "Audit reports"] },
    { code: "9.3", parent: "9", title: "Management review", sharedKey: "hls:9.3", guidance: "Top management reviews the system against the required inputs and records decisions and actions.", evidenceHints: ["Management review minutes"] },
    { code: "10", title: "Improvement" },
    { code: "10.1", parent: "10", title: "General", sharedKey: "hls:10.1", guidance: "Improve products and services, correct undesired effects and improve the system." },
    { code: "10.2", parent: "10", title: "Nonconformity and corrective action", sharedKey: "hls:10.2", guidance: "React to nonconformities including complaints, find causes, act, and check effectiveness.", evidenceHints: ["Corrective action log", "Complaint log"] },
    { code: "10.3", parent: "10", title: "Continual improvement", sharedKey: "hls:10.3", guidance: "Use analysis and management review outputs to improve.", evidenceHints: ["Improvement plan"] },
  ],
};
