// Shared shape and migration writer for the national factor libraries built from
// official workbooks (NGA Australia, ECCC Canada, UBA Germany, SEAI Ireland).
// Each builder (lib/factors/{nga,eccc,uba,seai}.ts) turns its workbook's rows
// into NationalFactor[]; this writes the additive migration SQL, the same
// pattern as the EPA Hub load (lib/factors/epa-hub.ts).

export type NationalFactor = {
  externalId: string;
  scope: 1 | 2 | 3;
  categoryCode: string;
  activityType: string;
  country: string;
  /** State, province or grid name; the factor is chosen by lib/calculation/regional-grid.ts. */
  region?: string | null;
  unit: string;
  co2?: number | null;
  ch4?: number | null;
  n2o?: number | null;
  co2e: number;
  biogenicCo2?: number | null;
  /** YYYY-MM-DD; null is open. */
  effectiveStart?: string | null;
  effectiveEnd?: string | null;
  notes: string;
};

export type NationalLibrary = {
  name: string;
  version: string;
  license: string;
  sourceUrl: string;
  /** YYYY-MM-DD */
  publishedAt: string;
};

export const round = (n: number, digits = 10) => Number(n.toPrecision(digits));
export const slug = (s: string) =>
  s
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/ß/g, "ss")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

export function assertUnique(factors: NationalFactor[]): void {
  const seen = new Set<string>();
  for (const f of factors) {
    if (seen.has(f.externalId)) throw new Error(`duplicate id ${f.externalId}`);
    seen.add(f.externalId);
    if (!Number.isFinite(f.co2e) || f.co2e < 0) throw new Error(`bad value for ${f.externalId}: ${f.co2e}`);
  }
}

const sql = (s: string) => `'${s.replace(/'/g, "''")}'`;
const num = (n: number | null | undefined) => (n == null ? "NULL" : String(n));
const date = (d: string | null | undefined) => (d ? `DATE '${d}'` : "NULL");

export function buildNationalMigrationSql(lib: NationalLibrary, factors: NationalFactor[], files: string[], comments: string[]): string {
  const counts = new Map<string, number>();
  for (const f of factors) counts.set(f.categoryCode, (counts.get(f.categoryCode) ?? 0) + 1);
  const rows = factors.map(
    (f) =>
      `    (${sql(f.externalId)}, ${f.scope}, ${sql(f.categoryCode)}, ${sql(f.activityType)}, ${sql(f.country)}, ${f.region ? sql(f.region) : "NULL"}, ${sql(f.unit)}, ${num(f.co2)}, ${num(f.ch4)}, ${num(f.n2o)}, ${num(f.co2e)}, ${num(f.biogenicCo2)}, ${date(f.effectiveStart)}, ${date(f.effectiveEnd)}, ${sql(f.notes)})`,
  );
  return `-- ${lib.name} ${lib.version}: ${factors.length} factors.
-- Generated by scripts/build-national-factors.ts from ${files.join(", ")}. Do not edit by hand.
-- Per category: ${[...counts].sort().map(([c, n]) => `${c} ${n}`).join(", ")}.
${comments.map((c) => `-- ${c}`).join("\n")}
-- Additive: inserts only what is missing.

INSERT INTO "factor_libraries" ("id", "name", "version", "license", "source_url", "published_at", "created_at")
VALUES (gen_random_uuid()::text, ${sql(lib.name)}, ${sql(lib.version)}, ${sql(lib.license)}, ${sql(lib.sourceUrl)}, DATE '${lib.publishedAt}', now())
ON CONFLICT ("name", "version") DO NOTHING;

WITH lib AS (
  SELECT "id" FROM "factor_libraries" WHERE "name" = ${sql(lib.name)} AND "version" = ${sql(lib.version)}
), src ("external_id", "scope", "category_code", "activity_type", "geography_country", "geography_region", "input_unit", "co2", "ch4", "n2o", "co2e", "biogenic_co2", "effective_start_date", "effective_end_date", "usage_notes") AS (
  VALUES
${rows.join(",\n")}
)
INSERT INTO "emission_factors" ("id", "factor_library_id", "external_id", "scope", "emission_category_id", "activity_type", "geography_country", "geography_region", "input_unit", "co2", "ch4", "n2o", "co2e", "biogenic_co2", "effective_start_date", "effective_end_date", "usage_notes")
SELECT gen_random_uuid()::text, lib."id", src."external_id", src."scope", c."id", src."activity_type", src."geography_country", src."geography_region"::text, src."input_unit", src."co2"::numeric, src."ch4"::numeric, src."n2o"::numeric, src."co2e"::numeric, src."biogenic_co2"::numeric, src."effective_start_date"::date, src."effective_end_date"::date, src."usage_notes"
FROM src
CROSS JOIN lib
JOIN "emission_categories" c ON c."code" = src."category_code"
ON CONFLICT ("factor_library_id", "external_id") DO NOTHING;
`;
}
