// EPA "Supply Chain Greenhouse Gas Emission Factors v1.3 by NAICS-6"
// (USEEIO). Each factor is kg CO2e per 2022 US dollar at purchaser prices,
// all GHGs combined with IPCC AR5 100-year GWPs, for one 2017 NAICS-6
// commodity. The "with margins" factor (SEF+MEF) is the one EPA recommends
// for spend recorded at purchaser prices, so that is what is loaded.
// Source: https://catalog.data.gov/dataset/supply-chain-greenhouse-gas-emission-factors-v1-3-by-naics-6
//
// Pure: parsing and SQL generation only. scripts/build-useeio-factors.ts
// reads the downloaded CSV and writes the migration.

export const USEEIO_LIBRARY = {
  name: "EPA USEEIO",
  version: "1.3",
  license: "Public Domain (US Government Work)",
  sourceUrl: "https://catalog.data.gov/dataset/supply-chain-greenhouse-gas-emission-factors-v1-3-by-naics-6",
  priceBaseYear: 2022,
  publishedAt: "2024-01-01",
} as const;

export type UseeioFactor = { naics: string; title: string; kgCo2ePerUsd: number };

/** Minimal RFC 4180 CSV parser (quoted fields, doubled quotes, CRLF). */
export function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let cur = "";
  let quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') { cur += '"'; i++; }
      else if (c === '"') quoted = false;
      else cur += c;
    } else if (c === '"') quoted = true;
    else if (c === ",") { row.push(cur); cur = ""; }
    else if (c === "\n" || c === "\r") {
      if (c === "\r" && text[i + 1] === "\n") i++;
      row.push(cur); cur = "";
      if (row.some((v) => v.trim() !== "")) rows.push(row);
      row = [];
    } else cur += c;
  }
  row.push(cur);
  if (row.some((v) => v.trim() !== "")) rows.push(row);
  return rows;
}

/**
 * Reads the v1.3 NAICS-6 CSV. Columns are found by name, not position, and
 * the file is refused rather than guessed at when one is missing or a row
 * does not say kg CO2e per 2022 USD.
 */
export function parseUseeioCsv(text: string): UseeioFactor[] {
  const [header, ...rows] = parseCsv(text.replace(/^﻿/, ""));
  if (!header) throw new Error("The file is empty.");
  const find = (re: RegExp, what: string) => {
    const i = header.findIndex((h) => re.test(h.trim()));
    if (i < 0) throw new Error(`No ${what} column. Header: ${header.join(" | ")}`);
    return i;
  };
  const code = find(/naics code/i, "NAICS code");
  const title = find(/naics title/i, "NAICS title");
  const withMargins = find(/with margins/i, "\"Supply Chain Emission Factors with Margins\"");
  const unitCol = header.findIndex((h) => /^unit$/i.test(h.trim()));

  const out: UseeioFactor[] = [];
  const seen = new Set<string>();
  for (const [n, r] of rows.entries()) {
    const naics = (r[code] ?? "").trim();
    if (!naics) continue;
    if (!/^\d{6}$/.test(naics)) throw new Error(`Row ${n + 2}: NAICS code "${naics}" is not 6 digits.`);
    if (unitCol >= 0 && r[unitCol] && !/kg\s*co2e.*2022.*usd/i.test(r[unitCol].replace(/\//g, " "))) {
      throw new Error(`Row ${n + 2}: unit "${r[unitCol]}" is not kg CO2e per 2022 USD.`);
    }
    const v = Number(r[withMargins]);
    if (!Number.isFinite(v) || v < 0) throw new Error(`Row ${n + 2}: factor "${r[withMargins]}" is not a number.`);
    if (seen.has(naics)) throw new Error(`Row ${n + 2}: NAICS ${naics} appears twice.`);
    seen.add(naics);
    out.push({ naics, title: (r[title] ?? "").trim(), kgCo2ePerUsd: v });
  }
  if (out.length === 0) throw new Error("No factor rows found.");
  return out;
}

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

/** Additive, idempotent migration: the library and its factors, price year 2022. */
export function buildUseeioMigrationSql(factors: UseeioFactor[], sourceFile: string): string {
  const L = USEEIO_LIBRARY;
  const values = factors
    .map((f) => `    (${q(`useeio-v1.3-naics6-${f.naics}`)}, ${q(`naics_${f.naics}`)}, ${f.kgCo2ePerUsd}, ${q(`NAICS ${f.naics}, ${f.title}. EPA USEEIO v1.3 supply chain factor with margins, kg CO2e per 2022 USD at purchaser prices (AR5 GWPs).`)})`)
    .join(",\n");
  return `-- EPA USEEIO v1.3 supply chain GHG emission factors by NAICS-6 (${factors.length} factors).
-- Generated by scripts/build-useeio-factors.ts from ${sourceFile}. Do not edit by hand.
-- kg CO2e per 2022 USD at purchaser prices, so price_base_year = 2022 and spend is
-- deflated to 2022 prices before the factor applies (lib/calculation/price-index.ts).
-- Additive: inserts only what is missing.

INSERT INTO "factor_libraries" ("id", "name", "version", "license", "source_url", "published_at", "created_at")
VALUES (gen_random_uuid()::text, ${q(L.name)}, ${q(L.version)}, ${q(L.license)}, ${q(L.sourceUrl)}, DATE ${q(L.publishedAt)}, now())
ON CONFLICT ("name", "version") DO NOTHING;

WITH lib AS (
  SELECT "id" FROM "factor_libraries" WHERE "name" = ${q(L.name)} AND "version" = ${q(L.version)}
), src ("external_id", "activity_type", "co2e", "usage_notes") AS (
  VALUES
${values}
)
INSERT INTO "emission_factors" (
  "id", "factor_library_id", "external_id", "scope", "emission_category_id", "activity_type",
  "geography_country", "input_unit", "co2e", "uncertainty_rating", "usage_notes", "price_base_year"
)
SELECT gen_random_uuid()::text, lib."id", src."external_id", c."scope", c."id", src."activity_type",
       'US', 'USD', src."co2e", 'high', src."usage_notes", ${L.priceBaseYear}
FROM src
JOIN "emission_categories" c ON c."code" = 's3-purchased-goods'
CROSS JOIN lib
WHERE NOT EXISTS (
  SELECT 1 FROM "emission_factors" e WHERE e."factor_library_id" = lib."id" AND e."external_id" = src."external_id"
);
`;
}
