import Link from "next/link";
import { BarChart3, ClipboardCheck, FileCheck, Lock, Smartphone, Users } from "lucide-react";
import { HeroSection } from "@/components/hero-section";
import { SiteFooter } from "@/components/marketing/site-footer";
import { StandardsMarquee } from "@/components/marketing/standards-marquee";
import { AnimateIn, AnimateInStagger } from "@/components/marketing/animate-in";
import { AnimatedCounter } from "@/components/marketing/animated-counter";

// Varied bento cells - deliberately NOT uniform 4-up cards.
const CAPABILITIES = [
  {
    title: "Field evidence capture",
    text: "Field workers photograph waste tickets and delivery notes. On-device OCR extracts weight, EWC codes, dates, and vehicle registrations. Works offline - syncs when connectivity returns.",
    icon: Smartphone,
    size: "md:col-span-2",
    accent: "#0f766e",
  },
  {
    title: "Six-role access control",
    text: "admin, editor, reviewer, viewer, auditor, field_worker. Each role precisely scoped to what that person needs to see and do.",
    icon: Users,
    size: "",
    accent: "#0ea5e9",
  },
  {
    title: "Calculation engine",
    text: "DEFRA 2025 + EPA GHG Hub factors. Scope 1, 2 and 3. GHG Protocol Corporate Standard with AR6 GWPs (CH4 = 27.9, N2O = 273). Every result stores the factor, formula, and methodology version.",
    icon: BarChart3,
    size: "",
    accent: "#84cc16",
  },
  {
    title: "Review workflow",
    text: "Submissions and imports land in a triage queue. Reviewers assign tasks, add comments, view evidence files, approve or reject with audit notes.",
    icon: ClipboardCheck,
    size: "",
    accent: "#8b5cf6",
  },
  {
    title: "Immutable snapshots and reports",
    text: "Publishing a snapshot locks a calculation run. Reports are generated by Puppeteer from the snapshot - totals will always match the dashboard for that version. PDF and CSV with SHA-256 checksums.",
    icon: FileCheck,
    size: "md:col-span-2",
    accent: "#f59e0b",
  },
  {
    title: "Append-only audit log",
    text: "Every auth event, role change, import, record mutation, calculation run, snapshot publication, and report download is written to an immutable audit log. Never updated or deleted.",
    icon: Lock,
    size: "",
    accent: "#f43f5e",
  },
];

const HOW_IT_WORKS = [
  {
    step: "01",
    title: "Collect evidence",
    text: "Field workers use the mobile app or web upload to capture activity data: waste tickets, fuel receipts, utility bills, travel records. CSV and XLSX imports handle bulk entry from existing systems.",
  },
  {
    step: "02",
    title: "Review and approve",
    text: "Submissions enter a review queue. Reviewers verify evidence, assign emission categories, add notes, and approve or reject. Approved records become committed ActivityRecords.",
  },
  {
    step: "03",
    title: "Calculate emissions",
    text: "Trigger a calculation run for a reporting period. The engine selects DEFRA or EPA factors by geography and activity type, normalises units, and computes CO2e using gas-specific GWP-100 values.",
  },
  {
    step: "04",
    title: "Publish and report",
    text: "Publish an immutable snapshot. Generate PDF and CSV reports. Download links are 15-minute signed URLs. Reports are auditable: every figure traces back to a factor, formula, and methodology version.",
  },
];

const STATS = [
  { to: 23, suffix: "", label: "Baseline emission factors seeded" },
  { to: 9, suffix: "", label: "Emission categories across Scope 1, 2 and 3" },
  { to: 6, suffix: "", label: "RBAC roles for web and mobile" },
  { to: 15, suffix: " min", label: "Presigned URL expiry for download security" },
];

export default function RootPage() {
  return (
    <main className="min-h-[100dvh] overflow-hidden">
      <HeroSection />

      {/* Standards marquee */}
      <StandardsMarquee />

      {/* Stats band */}
      <section className="bg-zinc-950 border-b border-zinc-800">
        <div className="mx-auto max-w-7xl px-5 py-14">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {STATS.map((stat, i) => (
              <AnimateIn key={stat.label} delay={i * 0.08}>
                <div className="text-center">
                  <div className="text-4xl md:text-5xl font-semibold tracking-tight text-white mb-2">
                    <AnimatedCounter to={stat.to} suffix={stat.suffix} />
                  </div>
                  <div className="text-sm text-zinc-500 leading-snug">{stat.label}</div>
                </div>
              </AnimateIn>
            ))}
          </div>
        </div>
      </section>

      {/* Capabilities bento */}
      <section className="bg-slate-50 border-b border-zinc-200">
        <div className="mx-auto max-w-7xl px-5 py-20">
          <AnimateIn>
            <div className="max-w-2xl mb-12">
              <h2 className="text-4xl md:text-5xl font-semibold tracking-tighter text-zinc-900 leading-tight mb-4">
                Built for the full carbon accounting workflow.
              </h2>
              <p className="text-base text-zinc-500 leading-relaxed max-w-[65ch]">
                From field evidence capture to board-ready reports, every stage is covered
                by purpose-built tooling rather than spreadsheet workarounds.
              </p>
            </div>
          </AnimateIn>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {CAPABILITIES.map((cap, i) => (
              <AnimateIn key={cap.title} delay={i * 0.06} className={cap.size}>
                <div className="h-full rounded-xl border border-zinc-200 bg-white p-6 hover:border-zinc-300 hover:shadow-sm transition-all">
                  <div
                    className="inline-flex h-9 w-9 items-center justify-center rounded-lg mb-4"
                    style={{ background: `${cap.accent}18`, color: cap.accent }}
                  >
                    <cap.icon className="h-4.5 w-4.5" />
                  </div>
                  <h3 className="text-sm font-semibold text-zinc-900 mb-2">{cap.title}</h3>
                  <p className="text-sm text-zinc-500 leading-relaxed">{cap.text}</p>
                </div>
              </AnimateIn>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="bg-zinc-950 border-b border-zinc-800">
        <div className="mx-auto max-w-7xl px-5 py-20">
          <AnimateIn>
            <h2 className="text-4xl md:text-5xl font-semibold tracking-tighter text-white mb-3">
              How it works.
            </h2>
            <p className="text-base text-zinc-400 leading-relaxed max-w-[55ch] mb-14">
              Four stages, end to end. No manual totalling, no spreadsheet risk.
            </p>
          </AnimateIn>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {HOW_IT_WORKS.map((step, i) => (
              <AnimateIn key={step.step} delay={i * 0.1}>
                <div className="relative h-full rounded-xl border border-zinc-800 bg-zinc-900 p-6">
                  <div className="text-5xl font-bold text-zinc-800 mb-4 tracking-tighter leading-none">
                    {step.step}
                  </div>
                  <h3 className="text-sm font-semibold text-white mb-2">{step.title}</h3>
                  <p className="text-sm text-zinc-400 leading-relaxed">{step.text}</p>
                  {i < HOW_IT_WORKS.length - 1 && (
                    <div className="hidden lg:block absolute top-1/2 -right-3 -translate-y-1/2 text-zinc-700 text-lg z-10">
                      -
                    </div>
                  )}
                </div>
              </AnimateIn>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-zinc-950">
        <div className="mx-auto max-w-3xl px-5 py-24 text-center">
          <AnimateIn>
            <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-12">
              <h2 className="text-3xl md:text-4xl font-semibold tracking-tighter text-white mb-4">
                Ready to track your carbon correctly?
              </h2>
              <p className="text-base text-zinc-400 leading-relaxed mb-8">
                Create a free organisation and run your first calculation in under an hour.
                No spreadsheet engineering. No paid APIs.
              </p>
              <div className="flex flex-col sm:flex-row gap-3 justify-center">
                <Link
                  href="/sign-up"
                  className="inline-flex items-center justify-center px-7 py-3 rounded-xl bg-emerald-600 text-white text-sm font-medium hover:bg-emerald-500 transition-colors active:scale-[0.97]"
                >
                  Create organisation
                </Link>
                <Link
                  href="/product"
                  className="inline-flex items-center justify-center px-7 py-3 rounded-xl border border-zinc-700 text-zinc-300 text-sm font-medium hover:border-zinc-500 hover:text-white transition-colors active:scale-[0.97]"
                >
                  Read the product overview
                </Link>
              </div>
            </div>
          </AnimateIn>
        </div>
      </section>

      <SiteFooter />
    </main>
  );
}
