// lib/reports/cbam-xml.ts
// CBAM (Carbon Border Adjustment Mechanism) XML Report Generator
//
// Implements the transitional reporting format per EU Implementing Reg 2023/1773
// and anticipates the UK CBAM framework (expected April 2027+).
//
// Covered goods (EU CBAM Annex I):
//   Cement (CN 2523), Iron/Steel (CN 72-73), Aluminium (CN 76),
//   Fertilisers (CN 28/31), Electricity (CN 2716), Hydrogen (CN 2804)

export interface CbamInstallation {
  name: string;
  country: string; // ISO 3166-1 alpha-2 (e.g. "DE", "CN", "TR")
  latitude?: number;
  longitude?: number;
}

export interface CbamGoodsItem {
  cnCode: string;        // Combined Nomenclature code (4-digit prefix)
  description: string;
  quantityTonnes: number;
  directEmbeddedCo2eTonnes: number;   // Direct process + energy emissions
  indirectEmbeddedCo2eTonnes: number; // Indirect (electricity) emissions
  carbonPricePaidGbp: number;         // Carbon cost already borne in origin country
  installation?: CbamInstallation;
}

export interface CbamReportData {
  declarantName: string;
  declarantEori?: string; // e.g. "GB123456789000"
  reportingPeriodLabel: string; // e.g. "Q1 2025"
  periodStart: Date;
  periodEnd: Date;
  submissionDate: Date;
  goodsItems: CbamGoodsItem[];
}

/** CN codes relevant to UK construction industry CBAM declarations */
export const CONSTRUCTION_CBAM_CN_CODES: Record<string, string> = {
  "2523": "Portland cement, aluminous cement and other hydraulic cements",
  "7207": "Semi-finished products of iron or non-alloy steel",
  "7208": "Flat-rolled products of iron/steel, hot-rolled, width ≥ 600 mm",
  "7209": "Flat-rolled products of iron/steel, cold-rolled, width ≥ 600 mm",
  "7213": "Bars and rods of iron/non-alloy steel, hot-rolled in irregular coils",
  "7214": "Bars and rods of iron/non-alloy steel, not further worked than forged",
  "7216": "Angles, shapes and sections of iron/non-alloy steel",
  "7217": "Wire of iron or non-alloy steel",
  "7228": "Bars and rods of other alloy steel",
  "7601": "Unwrought aluminium",
  "7604": "Aluminium bars, rods and profiles",
  "7606": "Aluminium plates, sheets and strip, thickness > 0.2 mm",
  "7610": "Aluminium structures and parts thereof",
  "2804": "Hydrogen",
  "3102": "Mineral or chemical fertilisers — nitrogenous (relevant for groundwork contractors)",
};

/** CBAM-covered good type enum for type-safe categorisation */
export type CbamMaterial = "cement" | "steel" | "aluminium" | "hydrogen" | "fertiliser" | "electricity";

/** Maps high-level material type to the most common CN code */
export const MATERIAL_TO_CN: Record<CbamMaterial, string> = {
  cement:      "2523",
  steel:       "7214",
  aluminium:   "7601",
  hydrogen:    "2804",
  fertiliser:  "3102",
  electricity: "2716",
};

// ── XML generation ────────────────────────────────────────────────────────────

function esc(s: string | number): string {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function fmtDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

function fmtN(n: number, dp = 6): string {
  return n.toFixed(dp);
}

/**
 * Generates a CBAM transitional-period XML report string.
 * Pure function — no database access. Pass pre-aggregated data from the worker.
 */
export function generateCbamXml(data: CbamReportData): string {
  const totalDirect   = data.goodsItems.reduce((s, g) => s + g.directEmbeddedCo2eTonnes, 0);
  const totalIndirect = data.goodsItems.reduce((s, g) => s + g.indirectEmbeddedCo2eTonnes, 0);
  const totalEmbedded = totalDirect + totalIndirect;

  const lines: string[] = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!--`,
    `  CBAM Transitional Period Report`,
    `  Reporting period : ${esc(data.reportingPeriodLabel)}`,
    `  Generated by     : CarbonSite`,
    `  Generated at     : ${fmtDate(data.submissionDate)}`,
    `  Regulation refs  : EU Reg 2023/956 + Implementing Reg 2023/1773`,
    `  Note             : UK CBAM applies from April 2027; use EU format until`,
    `                     HMRC publishes the UK XML schema.`,
    `-->`,
    `<CBAMReport`,
    `    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"`,
    `    schemaVersion="1.0">`,
    ``,
    `  <!-- ── Declarant ──────────────────────────────────────────────── -->`,
    `  <Declarant>`,
    `    <Name>${esc(data.declarantName)}</Name>`,
  ];

  if (data.declarantEori) {
    lines.push(`    <EORI>${esc(data.declarantEori)}</EORI>`);
  } else {
    lines.push(`    <!-- EORI: required for final CBAM submission — obtain from HMRC/EORI GB portal -->`);
  }

  lines.push(
    `  </Declarant>`,
    ``,
    `  <!-- ── Reporting period ───────────────────────────────────────── -->`,
    `  <ReportingPeriod>`,
    `    <Label>${esc(data.reportingPeriodLabel)}</Label>`,
    `    <StartDate>${fmtDate(data.periodStart)}</StartDate>`,
    `    <EndDate>${fmtDate(data.periodEnd)}</EndDate>`,
    `  </ReportingPeriod>`,
    ``,
    `  <SubmissionDate>${fmtDate(data.submissionDate)}</SubmissionDate>`,
    ``,
    `  <!-- ── Summary totals ─────────────────────────────────────────── -->`,
    `  <Summary>`,
    `    <TotalGoodsItems>${data.goodsItems.length}</TotalGoodsItems>`,
    `    <TotalDirectEmbeddedCO2eTonnes>${fmtN(totalDirect)}</TotalDirectEmbeddedCO2eTonnes>`,
    `    <TotalIndirectEmbeddedCO2eTonnes>${fmtN(totalIndirect)}</TotalIndirectEmbeddedCO2eTonnes>`,
    `    <TotalEmbeddedCO2eTonnes>${fmtN(totalEmbedded)}</TotalEmbeddedCO2eTonnes>`,
    `  </Summary>`,
    ``,
    `  <!-- ── Goods items ────────────────────────────────────────────── -->`,
    `  <GoodsItems>`,
  );

  for (const item of data.goodsItems) {
    const total     = item.directEmbeddedCo2eTonnes + item.indirectEmbeddedCo2eTonnes;
    const specific  = item.quantityTonnes > 0 ? total / item.quantityTonnes : 0;

    lines.push(`    <GoodsItem>`);
    lines.push(`      <CNCode>${esc(item.cnCode)}</CNCode>`);
    lines.push(`      <Description>${esc(item.description)}</Description>`);

    if (item.installation) {
      lines.push(`      <Installation>`);
      lines.push(`        <Name>${esc(item.installation.name)}</Name>`);
      lines.push(`        <CountryOfOrigin>${esc(item.installation.country)}</CountryOfOrigin>`);
      if (item.installation.latitude != null) {
        lines.push(`        <Coordinates>`);
        lines.push(`          <Latitude>${fmtN(item.installation.latitude, 4)}</Latitude>`);
        lines.push(`          <Longitude>${fmtN(item.installation.longitude ?? 0, 4)}</Longitude>`);
        lines.push(`        </Coordinates>`);
      }
      lines.push(`      </Installation>`);
    }

    lines.push(
      `      <ImportedQuantity>`,
      `        <Value>${fmtN(item.quantityTonnes, 3)}</Value>`,
      `        <Unit>tonne</Unit>`,
      `      </ImportedQuantity>`,
      `      <EmbeddedEmissions>`,
      `        <Direct>`,
      `          <CO2eTonnes>${fmtN(item.directEmbeddedCo2eTonnes)}</CO2eTonnes>`,
      `        </Direct>`,
      `        <Indirect>`,
      `          <CO2eTonnes>${fmtN(item.indirectEmbeddedCo2eTonnes)}</CO2eTonnes>`,
      `        </Indirect>`,
      `        <Total>`,
      `          <CO2eTonnes>${fmtN(total)}</CO2eTonnes>`,
      `          <SpecificCO2eTonnesPerTonne>${fmtN(specific)}</SpecificCO2eTonnesPerTonne>`,
      `        </Total>`,
      `      </EmbeddedEmissions>`,
      `      <CarbonPriceDue>`,
      `        <Currency>GBP</Currency>`,
      `        <Value>${fmtN(item.carbonPricePaidGbp, 2)}</Value>`,
      `      </CarbonPriceDue>`,
      `    </GoodsItem>`,
    );
  }

  lines.push(
    `  </GoodsItems>`,
    `</CBAMReport>`,
  );

  return lines.join("\n");
}

/**
 * Validates a CbamGoodsItem list for the most common submission errors.
 * Returns a list of human-readable error strings (empty = valid).
 */
export function validateCbamItems(items: CbamGoodsItem[]): string[] {
  const errors: string[] = [];
  if (items.length === 0) {
    errors.push("No CBAM goods items found — ensure Scope 3 purchased-goods records include material type metadata.");
    return errors;
  }
  for (const [i, item] of items.entries()) {
    const prefix = `Item ${i + 1} (${item.cnCode})`;
    if (!item.cnCode || !/^\d{4}$/.test(item.cnCode)) {
      errors.push(`${prefix}: CN code must be exactly 4 digits.`);
    }
    if (item.quantityTonnes <= 0) {
      errors.push(`${prefix}: Imported quantity must be > 0 tonnes.`);
    }
    if (item.directEmbeddedCo2eTonnes < 0) {
      errors.push(`${prefix}: Direct embedded CO₂e cannot be negative.`);
    }
    if (item.indirectEmbeddedCo2eTonnes < 0) {
      errors.push(`${prefix}: Indirect embedded CO₂e cannot be negative.`);
    }
    if (item.carbonPricePaidGbp < 0) {
      errors.push(`${prefix}: Carbon price paid cannot be negative.`);
    }
    if (item.installation && item.installation.country.length !== 2) {
      errors.push(`${prefix}: Country of origin must be a 2-letter ISO code.`);
    }
  }
  return errors;
}
