-- Originally: "Add n8n workflow orchestration tracking tables".
--
-- Neutralized. This migration used UUID ids/organization_id (copy-pasted
-- from an illustrative planning doc) referencing organizations(id), which
-- is TEXT (Prisma cuid()) — CREATE TABLE always failed here, so
-- n8n_workflows/n8n_workflow_executions were never actually created,
-- despite _prisma_migrations recording this migration as applied.
--
-- It's also superseded, not just broken: the column shape here
-- (trigger_type/webhook_url, no action/last_execution_status/
-- execution_count) predates a schema redesign and no longer matches the
-- N8nWorkflow/N8nExecution Prisma models. The later migration
-- 20260831000002_add_airbyte_n8n_dbt_models already creates
-- "n8n_workflows"/"n8n_executions" with the current, correct shape via
-- CREATE TABLE IF NOT EXISTS — so fixing the types here to match this
-- migration's outdated column names would just create the wrong shape and
-- block that later migration from ever installing the right one (IF NOT
-- EXISTS skips silently once a table exists). Left intentionally empty.
