-- ADEME Base Carbone, export last modified 2025-04-24 (27 factors, in addition to 5254 loaded by an earlier migration).
-- Generated by scripts/build-ademe-factors.ts from ademe-base-carbone.csv. Do not edit by hand.
-- Licence Ouverte v2.0. Mapping and what is left out: lib/factors/ademe.ts.
-- Rows not loaded, by reason:
--   4421 status Archivé
--   1878 not an emission factor (source data)
--   219 electricity: France split by end use or production, not the annual average mix
--   197 land use change (UTCF): per hectare, GHG Protocol Land Sector standard
--   138 fuel: same factor in another unit
--   71 status Valide spécifique
--   58 fuel: no combustion post
--   56 spend: earlier year (2019)
--   56 spend: earlier year (2020)
--   56 spend: earlier year (2021)
--   56 spend: earlier year (2022)
--   50 fuel: region without a country
--   46 goods: unit kgCO2e/m²
--   45 goods: region without a country
--   43 goods: unit kgCO2e/appareil
--   40 category not mapped: Statistiques territoriales
--   24 electricity: region without a country
--   19 category not mapped: Achats de services
--   15 goods: unit kgCO2e/kgH2
--   14 category not mapped: Process et émissions fugitives
--   11 category not mapped: Electricité
--   10 spend: no NAF division
--   6 freight_transport: region without a country
--   5 passenger_transport: region without a country
--   4 goods: unit kgCO2e/mL
--   4 goods: unit kgCO2e/kg de cuir traité
--   4 freight_transport: unit kgCO2e/km
--   3 freight_transport: unit kgCO2e/m3.km
--   3 goods: unit kgCO2e/m² SHON
--   3 goods: unit kgCO2e/m
--   3 goods: unit kgCO2e/100 feuilles A4
--   3 goods: unit kgCO2e/m² de paroi
--   3 goods: unit kgCO2e/m de route
--   2 goods: unit kgCO2e/euro dépensé
--   2 fuel: unit kgCO2e/TEP PCS
--   2 goods: unit kgCO2e/kg de matière active
--   2 goods: unit kgCO2e/kgH2/100km
--   1 fuel: unit kgCO2e/kg BioGNC
--   1 fuel: unit kgCO2e/kWh (PCI)
--   1 goods: unit kgCO2e/m³
--   1 electricity: France comes from its annual mix
--   1 fuel: unit kgCO2e/tep PCS
--   1 passenger_transport: unit kgCO2e/heure
--   1 goods: unit kgCO2e/livre
--   1 goods: unit kgCO2e/m2 SHON
--   1 goods: unit kgCO2e/keuro
--   1 goods: unit kgCO2e/litre
--   1 goods: unit kgCO2e/m² de sol
--   1 waste_treatment: unit kgCO2e/m3
--   1 goods: unit kgCO2e/m² de toiture
-- Additive: inserts only what is missing.

INSERT INTO "factor_libraries" ("id", "name", "version", "license", "source_url", "published_at", "created_at")
VALUES (gen_random_uuid()::text, 'ADEME Base Carbone', '2025.04', 'Licence Ouverte v2.0 (Etalab)', 'https://data.ademe.fr/datasets/base-carboner', DATE '2025-04-24', now())
ON CONFLICT ("name", "version") DO NOTHING;

WITH lib AS (
  SELECT "id" FROM "factor_libraries" WHERE "name" = 'ADEME Base Carbone' AND "version" = '2025.04'
), src ("external_id", "category_code", "activity_type", "geography_country", "input_unit", "co2e", "biogenic_co2", "price_base_year", "effective_start_date", "effective_end_date", "usage_notes") AS (
  VALUES
    ('ademe-28159', 's3-upstream-transport', 'freight_transport', 'DE', 'tonne.km', 0.032, NULL, NULL, NULL::date, NULL::date, 'Train (freight) (Train de marchandises) (ADEME 28159).'),
    ('ademe-28160', 's3-upstream-transport', 'freight_transport', 'AT', 'tonne.km', 0.0126, NULL, NULL, NULL::date, NULL::date, 'Train (freight) (Train de marchandises) (ADEME 28160).'),
    ('ademe-28161', 's3-upstream-transport', 'freight_transport', 'BE', 'tonne.km', 0.0186, NULL, NULL, NULL::date, NULL::date, 'Train (freight) (Train de marchandises) (ADEME 28161).'),
    ('ademe-28162', 's3-upstream-transport', 'freight_transport', 'DK', 'tonne.km', 0.0378, NULL, NULL, NULL::date, NULL::date, 'Train (freight) (Train de marchandises) (ADEME 28162).'),
    ('ademe-28163', 's3-upstream-transport', 'freight_transport', 'ES', 'tonne.km', 0.0345, NULL, NULL, NULL::date, NULL::date, 'Train (freight) (Train de marchandises) (ADEME 28163).'),
    ('ademe-28164', 's3-upstream-transport', 'freight_transport', 'FI', 'tonne.km', 0.0201, NULL, NULL, NULL::date, NULL::date, 'Train (freight) (Train de marchandises) (ADEME 28164).'),
    ('ademe-28165', 's3-upstream-transport', 'freight_transport', 'GR', 'tonne.km', 0.0445, NULL, NULL, NULL::date, NULL::date, 'Train (freight) (Train de marchandises) (ADEME 28165).'),
    ('ademe-28168', 's3-upstream-transport', 'freight_transport', 'LU', 'tonne.km', 0.0253, NULL, NULL, NULL::date, NULL::date, 'Train (freight) (Train de marchandises) (ADEME 28168).'),
    ('ademe-28169', 's3-upstream-transport', 'freight_transport', 'NO', 'tonne.km', 0.00822, NULL, NULL, NULL::date, NULL::date, 'Train (freight) (Train de marchandises) (ADEME 28169).'),
    ('ademe-28171', 's3-upstream-transport', 'freight_transport', 'PT', 'tonne.km', 0.0444, NULL, NULL, NULL::date, NULL::date, 'Train (freight) (Train de marchandises) (ADEME 28171).'),
    ('ademe-28172', 's3-upstream-transport', 'freight_transport', 'GB', 'tonne.km', 0.0412, NULL, NULL, NULL::date, NULL::date, 'Train (freight) (Train de marchandises) (ADEME 28172).'),
    ('ademe-28173', 's3-upstream-transport', 'freight_transport', 'SE', 'tonne.km', 0.00428, NULL, NULL, NULL::date, NULL::date, 'Train (freight) (Train de marchandises) (ADEME 28173).'),
    ('ademe-28174', 's3-upstream-transport', 'freight_transport', 'CH', 'tonne.km', 0.00364, NULL, NULL, NULL::date, NULL::date, 'Train (freight) (Train de marchandises) (ADEME 28174).'),
    ('ademe-28177', 's3-business-travel', 'passenger_transport', 'DE', 'passenger.km', 0.0668, NULL, NULL, NULL::date, NULL::date, 'Train (passengers) (Train de voyageurs) (ADEME 28177).'),
    ('ademe-28178', 's3-business-travel', 'passenger_transport', 'AT', 'passenger.km', 0.0235, NULL, NULL, NULL::date, NULL::date, 'Train (passengers) (Train de voyageurs) (ADEME 28178).'),
    ('ademe-28179', 's3-business-travel', 'passenger_transport', 'BE', 'passenger.km', 0.0484, NULL, NULL, NULL::date, NULL::date, 'Train (passengers) (Train de voyageurs) (ADEME 28179).'),
    ('ademe-28180', 's3-business-travel', 'passenger_transport', 'DK', 'passenger.km', 0.114, NULL, NULL, NULL::date, NULL::date, 'Train (passengers) (Train de voyageurs) (ADEME 28180).'),
    ('ademe-28181', 's3-business-travel', 'passenger_transport', 'ES', 'passenger.km', 0.0514, NULL, NULL, NULL::date, NULL::date, 'Train (passengers) (Train de voyageurs) (ADEME 28181).'),
    ('ademe-28182', 's3-business-travel', 'passenger_transport', 'FI', 'passenger.km', 0.0452, NULL, NULL, NULL::date, NULL::date, 'Train (passengers) (Train de voyageurs) (ADEME 28182).'),
    ('ademe-28183', 's3-business-travel', 'passenger_transport', 'GR', 'passenger.km', 0.0662, NULL, NULL, NULL::date, NULL::date, 'Train (passengers) (Train de voyageurs) (ADEME 28183).'),
    ('ademe-28185', 's3-business-travel', 'passenger_transport', 'IT', 'passenger.km', 0.0317, NULL, NULL, NULL::date, NULL::date, 'Train (passengers) (Train de voyageurs) (ADEME 28185).'),
    ('ademe-28186', 's3-business-travel', 'passenger_transport', 'LU', 'passenger.km', 0.0397, NULL, NULL, NULL::date, NULL::date, 'Train (passengers) (Train de voyageurs) (ADEME 28186).'),
    ('ademe-28187', 's3-business-travel', 'passenger_transport', 'NO', 'passenger.km', 0.04, NULL, NULL, NULL::date, NULL::date, 'Train (passengers) (Train de voyageurs) (ADEME 28187).'),
    ('ademe-28189', 's3-business-travel', 'passenger_transport', 'PT', 'passenger.km', 0.0615, NULL, NULL, NULL::date, NULL::date, 'Train (passengers) (Train de voyageurs) (ADEME 28189).'),
    ('ademe-28190', 's3-business-travel', 'passenger_transport', 'GB', 'passenger.km', 0.075, NULL, NULL, NULL::date, NULL::date, 'Train (passengers) (Train de voyageurs) (ADEME 28190).'),
    ('ademe-28191', 's3-business-travel', 'passenger_transport', 'SE', 'passenger.km', 0.0129, NULL, NULL, NULL::date, NULL::date, 'Train (passengers) (Train de voyageurs) (ADEME 28191).'),
    ('ademe-28192', 's3-business-travel', 'passenger_transport', 'CH', 'passenger.km', 0.00374, NULL, NULL, NULL::date, NULL::date, 'Train (passengers) (Train de voyageurs) (ADEME 28192).')
)
INSERT INTO "emission_factors" (
  "id", "factor_library_id", "external_id", "scope", "emission_category_id", "activity_type", "geography_country",
  "input_unit", "co2e", "biogenic_co2", "price_base_year", "effective_start_date", "effective_end_date", "usage_notes"
)
SELECT gen_random_uuid()::text, lib."id", src."external_id", c."scope", c."id", src."activity_type", src."geography_country",
       src."input_unit", src."co2e"::numeric, src."biogenic_co2"::numeric, src."price_base_year"::int, src."effective_start_date", src."effective_end_date", src."usage_notes"
FROM src
JOIN "emission_categories" c ON c."code" = src."category_code"
CROSS JOIN lib
WHERE NOT EXISTS (
  SELECT 1 FROM "emission_factors" e WHERE e."factor_library_id" = lib."id" AND e."external_id" = src."external_id"
);
