-- Originally: a second attempt at "invoice_records"/"invoice_anomalies",
-- one day after 20260828000001_add_invoice_anomaly_detection.
--
-- Neutralized. This used an outdated column shape (currency,
-- source_record_id, status) that doesn't match the current InvoiceRecord/
-- InvoiceAnomaly Prisma models (payment_status, scope3_ready_status,
-- due_date, processed_at, updated_at — no currency/source_record_id/status
-- at all). Since 20260828000001 (fixed elsewhere in this same repair pass)
-- already creates both tables with the correct, current shape via CREATE
-- TABLE IF NOT EXISTS, this migration's own CREATE TABLE statements just
-- no-op — but its CREATE INDEX ...("organization_id", "status") then fails
-- outright, because the real invoice_records table has no "status" column.
-- Its one non-redundant piece — backfilling organization_id onto
-- invoice_reconciliations — is also already handled: that fix's rewrite of
-- 20260828000001 creates invoice_reconciliations with organization_id
-- NOT NULL from the start. Left intentionally empty.
